"""Unit tests for the geometry pipeline (tools/fetch_zg3d.py, fetch_dtm.py, fetch_osm.py, build_env.py).

Run:  python3 -m unittest discover -s tests/python -v      (no network: saved fixtures only)

Fixtures (tests/python/fixtures/)
    geo_zg3d_sample.json   4 real ZG3D features (embedMaterials, outSR=4326): FirstRing triangles,
                           a TriangleFan part, an OuterRing + InnerRing part, a single OuterRing face
    geo_tiny_dtm.tif       a 5 x 4 float64 GeoTIFF with the DGU tile's layout (1 row per strip,
                           uncompressed, EPSG:3045, PixelIsArea, nodata -9999); regenerated by tiny_tiff()

What is covered
    1. binaryPatches decoding (part types, vertex counts, Z within the part's Z_Min/Z_Max)
    2. Transverse Mercator: the DHMZ point in EPSG:3765 and EPSG:3045 (lidar-3d §1), round trip, and the
       northing on the central meridian against an independent numerical meridian-arc integral
    3. TIFF IFD parsing, strip reading (contiguous and not) and bilinear sampling with nodata
    4. the ear-clipping triangulator: concave polygons and polygons with holes conserve area
    5. env.json / lod2.bin schema (architecture §4.1) on the committed build output
    6. road class, group and AADT rules (critic §4.6), the Miramarska override (critic §1.6), OSM height
       fallbacks (critic §1.9), Macdonald morphometry (critic §1.10) and small geometry helpers
"""
from __future__ import annotations

import json
import math
import struct
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools"))

import build_env as be  # noqa: E402
import fetch_dtm as fd  # noqa: E402
import fetch_osm as fo  # noqa: E402
import fetch_zg3d as fz  # noqa: E402
from common import SITE, bbox_latlon, latlon, ring_area, xz  # noqa: E402

FIX = Path(__file__).resolve().parent / "fixtures"
ENV = ROOT / "src" / "data" / "env.json"
LOD2 = ROOT / "src" / "data" / "lod2.bin"


# ------------------------------------------------------------------ fixture writers
TINY_E0, TINY_N0, TINY_PX = 575690.0, 5072360.0, 20.0   # NW corner of the tiny tile (EPSG:3045), near ZAGREB-1
TINY_W, TINY_H = 5, 4
TINY_NODATA = (3, 4)                                     # (row, col) set to -9999


def tiny_value(r: int, c: int) -> float:
    """A plane h = 100 + 0.5 c - 0.25 r, so bilinear interpolation is exact."""
    return 100.0 + 0.5 * c - 0.25 * r


def tiny_tiff(contiguous: bool = True) -> bytes:
    """A minimal GeoTIFF with the RH_ELEV_107 layout. contiguous=False writes the strips in reverse order."""
    rows = []
    for r in range(TINY_H):
        vals = [(-9999.0 if (r, c) == TINY_NODATA else tiny_value(r, c)) for c in range(TINY_W)]
        rows.append(struct.pack("<%dd" % TINY_W, *vals))
    geokeys = [1, 1, 0, 3, 1024, 0, 1, 1, 1025, 0, 1, 1, 3072, 0, 1, 3045]
    entries = [  # (tag, type, count, payload bytes)
        (256, 3, 1, struct.pack("<H", TINY_W)), (257, 3, 1, struct.pack("<H", TINY_H)),
        (258, 3, 1, struct.pack("<H", 64)), (259, 3, 1, struct.pack("<H", 1)), (262, 3, 1, struct.pack("<H", 1)),
        (273, 4, TINY_H, None), (277, 3, 1, struct.pack("<H", 1)), (278, 3, 1, struct.pack("<H", 1)),
        (279, 4, TINY_H, struct.pack("<%dI" % TINY_H, *([TINY_W * 8] * TINY_H))),
        (284, 3, 1, struct.pack("<H", 1)), (339, 3, 1, struct.pack("<H", 3)),
        (33550, 12, 3, struct.pack("<3d", TINY_PX, TINY_PX, 0.0)),
        (33922, 12, 6, struct.pack("<6d", 0.0, 0.0, 0.0, TINY_E0, TINY_N0, 0.0)),
        (34735, 3, len(geokeys), struct.pack("<%dH" % len(geokeys), *geokeys)),
        (42113, 2, 6, b"-9999\0"),
    ]
    n = len(entries)
    ifd_size = 2 + 12 * n + 4
    data_off = 8 + ifd_size
    blobs, offsets = b"", {}
    for tag, _typ, _cnt, payload in entries:
        if payload is not None and len(payload) > 4:
            offsets[tag] = data_off + len(blobs)
            blobs += payload + (b"\0" if len(payload) % 2 else b"")
    strip_arr_off = data_off + len(blobs)
    blobs += b"\0" * (4 * TINY_H)
    strips_off = data_off + len(blobs)
    order = list(range(TINY_H)) if contiguous else list(reversed(range(TINY_H)))
    strip_offsets = [0] * TINY_H
    strips = b""
    for r in order:
        strip_offsets[r] = strips_off + len(strips)
        strips += rows[r]
    blobs = blobs[:strip_arr_off - data_off] + struct.pack("<%dI" % TINY_H, *strip_offsets) + blobs[strip_arr_off - data_off + 4 * TINY_H:]
    ifd = struct.pack("<H", n)
    for tag, typ, cnt, payload in entries:
        if tag == 273:
            ifd += struct.pack("<HHII", tag, typ, cnt, strip_arr_off)
        elif len(payload) > 4:
            ifd += struct.pack("<HHII", tag, typ, cnt, offsets[tag])
        else:
            ifd += struct.pack("<HHI", tag, typ, cnt) + payload.ljust(4, b"\0")
    ifd += struct.pack("<I", 0)
    return b"II" + struct.pack("<HI", 42, 8) + ifd + blobs + strips


def bytes_reader(data: bytes) -> fd.Reader:
    def read(offset: int, length: int) -> bytes:
        out = data[offset:offset + length]
        if len(out) != length:
            raise IOError("short read")
        return out
    return read


# ------------------------------------------------------------------ 1. binaryPatches
class TestBinaryPatches(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.page = json.loads((FIX / "geo_zg3d_sample.json").read_text(encoding="utf-8"))
        cls.feats = {f["attributes"]["OBJECTID"]: f for f in cls.page["features"]}

    def decode(self, oid):
        return fz.decode_binary_patches(self.feats[oid]["geometry"]["binaryPatches"])

    def test_first_ring_part(self):
        pp = self.decode(60300)
        self.assertEqual(len(pp), 76)
        self.assertTrue(all(t == fz.FIRST_RING and len(r) == 5 for t, r in pp))
        lon, lat, z = pp[0][1][0]
        self.assertAlmostEqual(lon, 15.965487273, places=8)
        self.assertAlmostEqual(lat, 45.805778222, places=8)
        self.assertAlmostEqual(z, 115.8966, places=3)

    def test_part_types(self):
        self.assertEqual({t for t, _ in self.decode(351605)}, {fz.TRIANGLE_FAN})
        self.assertEqual({t for t, _ in self.decode(353639)}, {fz.OUTER_RING, fz.INNER_RING})
        self.assertEqual([(t, len(r)) for t, r in self.decode(352697)], [(fz.OUTER_RING, 5)])

    def test_z_within_attributes(self):
        for oid, f in self.feats.items():
            a = f["attributes"]
            zs = [z for _, r in self.decode(oid) for _, _, z in r]
            self.assertGreaterEqual(min(zs), a["Z_Min"] - 0.01, oid)
            self.assertLessEqual(max(zs), a["Z_Max"] + 0.01, oid)

    def test_coordinates_in_scene_box(self):
        s, w, n, e = bbox_latlon(SITE["extent"]["scene_half_m"] + 50)
        for oid in self.feats:
            for _, r in self.decode(oid):
                for lon, lat, _ in r:
                    self.assertTrue(w <= lon <= e and s <= lat <= n)

    def test_triangulated_surface_area(self):
        """The triangles cover every face exactly: their area equals the Newell areas of the rings (outer
        minus inner rings), and never exceeds the part's closed-surface attribute SArea (+1 % for the local
        frame's scale; ZG3D multipatches often have no bottom face, which SArea counts)."""
        for oid, f in self.feats.items():
            loc = [(t, [(*xz(lat, lon), Z) for lon, lat, Z in r]) for t, r in self.decode(oid)]
            patches = [(t, [(x, Z, z) for x, z, Z in r]) for t, r in loc]
            tris = fz.triangulate_patches(patches)
            area = sum(fz.tri_area_3d(*t) for t in tris)
            exp = 0.0
            for t, r in patches:
                if t in (fz.TRIANGLE_FAN,):
                    exp += sum(fz.tri_area_3d(r[0], r[i], r[i + 1]) for i in range(1, len(r) - 1))
                    continue
                a = 0.5 * math.sqrt(sum(c * c for c in fz.newell_normal(fz._clean_ring(r))))
                exp += -a if t in (fz.INNER_RING, fz.RING) else a
            self.assertAlmostEqual(area, exp, delta=1e-6 * exp, msg=oid)
            self.assertLess(area, 1.01 * f["attributes"]["SArea"], oid)

    def test_query_urls(self):
        u = fz.query_url("lod2", 500, 750)
        for s in ("outSR=4326", "inSR=4326", "multipatchOption=embedMaterials", "returnZ=true", "resultOffset=500"):
            self.assertIn(s, u)
        u = fz.query_url("fp", 0, 750)
        self.assertIn("multipatchOption=xyFootprint", u)
        self.assertIn("f=geojson", u)


# ------------------------------------------------------------------ 2. projections
class TestTransverseMercator(unittest.TestCase):
    LAT, LON = SITE["station"]["lat"], SITE["station"]["lon"]

    def test_station_3765(self):
        e, n = fd.tm_forward(self.LAT, self.LON, fd.PROJ_3765)
        self.assertAlmostEqual(e, SITE["frame"]["htrs96_e0"], delta=0.002)   # lidar-3d §1: 459129.318
        self.assertAlmostEqual(n, SITE["frame"]["htrs96_n0"], delta=0.002)   # 5073538.234

    def test_station_3045(self):
        e, n = fd.tm_forward(self.LAT, self.LON, fd.PROJ_3045)
        self.assertAlmostEqual(e, 575706.67, delta=0.01)                   # lidar-3d §1
        self.assertAlmostEqual(n, 5072343.07, delta=0.01)

    def test_round_trip(self):
        for lat in (42.4, 44.0, 45.8, 46.5):
            for lon in (13.5, 15.0, 15.97422, 16.5, 19.4):
                for proj in (fd.PROJ_3765, fd.PROJ_3045):
                    e, n = fd.tm_forward(lat, lon, proj)
                    la, lo = fd.tm_inverse(e, n, proj)
                    self.assertAlmostEqual(la, lat, places=10)
                    self.assertAlmostEqual(lo, lon, places=10)

    def test_central_meridian_arc(self):
        """On the central meridian N = k0 * meridian arc; the arc is integrated numerically (Simpson) from
        M(phi) = a (1 - e^2) / (1 - e^2 sin^2 phi)^(3/2), independently of the Krüger series."""
        a, f = fd.GRS80_A, fd.GRS80_F
        e2 = f * (2 - f)
        for lat in (10.0, 45.0, 45.800496, 60.0):
            phi, m = math.radians(lat), 2000
            h = phi / m
            s = 0.0
            for i in range(m + 1):
                p = i * h
                w = 1 if i in (0, m) else (4 if i % 2 else 2)
                s += w * a * (1 - e2) / (1 - e2 * math.sin(p) ** 2) ** 1.5
            arc = s * h / 3
            _e, n = fd.tm_forward(lat, fd.PROJ_3045["lon0"], fd.PROJ_3045)
            self.assertAlmostEqual(n, fd.PROJ_3045["k0"] * arc, delta=0.001)

    def test_local_to_3045_origin(self):
        e, n = fd.local_to_3045(0.0, 0.0)
        self.assertAlmostEqual(e, 575706.67, delta=0.01)
        self.assertAlmostEqual(n, 5072343.07, delta=0.01)


# ------------------------------------------------------------------ 3. TIFF
class TestTiff(unittest.TestCase):
    def test_fixture_is_current(self):
        self.assertEqual((FIX / "geo_tiny_dtm.tif").read_bytes(), tiny_tiff(), "regenerate with tiny_tiff()")

    def test_ifd(self):
        g = fd.tiff_geometry(fd.file_reader(FIX / "geo_tiny_dtm.tif"))
        self.assertEqual((g["width"], g["height"], g["bits"], g["compression"]), (TINY_W, TINY_H, 64, 1))
        self.assertEqual((g["rows_per_strip"], g["sample_format"], g["raster_type"], g["epsg"]), (1, 3, 1, 3045))
        self.assertEqual(g["nodata"], -9999.0)
        self.assertEqual(g["pixel"], (TINY_PX, TINY_PX))
        self.assertEqual(g["tiepoint"][3:5], [TINY_E0, TINY_N0])
        self.assertEqual(g["row_bytes"], TINY_W * 8)
        e, n = fd.pixel_centre(g, 0, 0)
        self.assertEqual((e, n), (TINY_E0 + 10.0, TINY_N0 - 10.0))          # PixelIsArea: centre = corner + half
        self.assertEqual(fd.pixel_of(g, e, n), (0.0, 0.0))

    def test_window_contiguous_and_not(self):
        for contiguous in (True, False):
            data = tiny_tiff(contiguous)
            g = fd.tiff_geometry(bytes_reader(data))
            rows, info = fd.read_window(bytes_reader(data), g, 1, 3, 1, 3)
            self.assertEqual(info["contiguous"], contiguous)
            self.assertEqual(len(rows), 3)
            self.assertEqual(rows[0], [tiny_value(1, c) for c in (1, 2, 3)])
            self.assertEqual(rows[2][2], tiny_value(3, 3))

    def test_bilinear_and_nodata(self):
        g = fd.tiff_geometry(fd.file_reader(FIX / "geo_tiny_dtm.tif"))
        rows, _ = fd.read_window(fd.file_reader(FIX / "geo_tiny_dtm.tif"), g, 0, TINY_H - 1, 0, TINY_W - 1)
        e0, n0 = fd.pixel_centre(g, 0, 0)
        dtm = fd.DTM({"e0": e0, "n0": n0, "de": TINY_PX, "dn": TINY_PX, "nc": TINY_W, "nr": TINY_H,
                      "nodata": -9999.0, "h": [v for r in rows for v in r]})
        for c, r in ((0, 0), (1.5, 0.5), (2.25, 1.75), (3.0, 2.0)):
            self.assertAlmostEqual(dtm.at_en(e0 + c * TINY_PX, n0 - r * TINY_PX), 100 + 0.5 * c - 0.25 * r, places=9)
        near = dtm.at_en(e0 + 3.9 * TINY_PX, n0 - 2.9 * TINY_PX)       # next to the nodata pixel (3, 4)
        self.assertGreater(near, 90.0)
        self.assertLess(near, 110.0)

    def test_not_a_tiff(self):
        with self.assertRaises(ValueError):
            fd.parse_tiff_header(bytes_reader(b"GIF89a" + b"\0" * 32))


# ------------------------------------------------------------------ 4. triangulator
def area2d(tris3, ax=(0, 2)):
    return sum(abs((b[ax[0]] - a[ax[0]]) * (c[ax[1]] - a[ax[1]]) - (b[ax[1]] - a[ax[1]]) * (c[ax[0]] - a[ax[0]])) / 2
               for a, b, c in tris3)


class TestTriangulator(unittest.TestCase):
    PLANES = {
        "xz": lambda u, v: (u, 0.0, v),
        "xy": lambda u, v: (u, v, 0.0),
        "yz": lambda u, v: (0.0, u, v),
        "tilted": lambda u, v: (u, 0.5 * u + 0.3 * v, v),
    }

    def check(self, outer, holes=(), exp=None):
        exp = abs(ring_area(outer)) - sum(abs(ring_area(h)) for h in holes) if exp is None else exp
        for name, f in self.PLANES.items():
            for rev in (False, True):
                o = [f(*p) for p in (outer[::-1] if rev else outer)]
                hs = [[f(*p) for p in h] for h in holes]
                tris = fz.triangulate_polygon_3d(o, hs)
                full = fz.triangulate_polygon_3d([f(*p) for p in [(0, 0), (1, 0), (1, 1), (0, 1)]])
                scale = sum(fz.tri_area_3d(*t) for t in full)          # plane stretch factor
                got = sum(fz.tri_area_3d(*t) for t in tris) / scale
                self.assertAlmostEqual(got, exp, places=6, msg=f"{name} rev={rev}")
                n_exp = len(outer) + sum(len(h) for h in holes) + 2 * len(holes) - 2
                self.assertLessEqual(len(tris), n_exp, name)

    def test_convex(self):
        self.check([(0, 0), (4, 0), (4, 3), (0, 3)])

    def test_L_shape(self):
        self.check([(0, 0), (10, 0), (10, 3), (3, 3), (3, 8), (0, 8)])

    def test_comb(self):
        self.check([(0, 0), (20, 0), (20, 10), (17, 10), (17, 3), (14, 3), (14, 10), (11, 10), (11, 3), (8, 3),
                    (8, 10), (5, 10), (5, 3), (2, 3), (2, 10), (0, 10)])

    def test_star(self):
        star = [((10 if i % 2 == 0 else 4) * math.cos(i * math.pi / 10), (10 if i % 2 == 0 else 4) * math.sin(i * math.pi / 10))
                for i in range(20)]
        self.check(star)

    def test_collinear_and_duplicates(self):
        self.check([(0, 0), (2, 0), (4, 0), (4, 0), (4, 2), (4, 4), (0, 4), (0, 0)], exp=16.0)

    def test_holes(self):
        sq = [(0, 0), (10, 0), (10, 10), (0, 10)]
        self.check(sq, [[(2, 2), (4, 2), (4, 4), (2, 4)]])
        self.check(sq, [[(2, 2), (4, 2), (4, 4), (2, 4)], [(6, 6), (8, 6), (8, 8), (6, 8)]])
        # holes sharing a bridge target (the nesting case of fetch_zg3d._wedge_copy)
        self.check(sq, [[(1, 1), (2, 1), (2, 2), (1, 2)], [(1, 5), (2, 5), (2, 6), (1, 6)], [(1, 8), (2, 8), (2, 9), (1, 9)]])

    def test_concave_with_hole(self):
        self.check([(0, 0), (12, 0), (12, 12), (8, 12), (8, 4), (4, 4), (4, 12), (0, 12)],
                   [[(1, 1), (3, 1), (3, 3), (1, 3)], [(9, 5), (11, 5), (11, 9), (9, 9)]])

    def test_patch_types(self):
        strip = [(0, 0, 0), (0, 1, 0), (1, 0, 0), (1, 1, 0), (2, 0, 0)]
        tris = fz.triangulate_patches([(fz.TRIANGLE_STRIP, strip)])
        self.assertEqual(len(tris), 3)
        self.assertAlmostEqual(area2d(tris, (0, 1)), 1.5)
        normals = [fz.newell_normal(list(t))[2] for t in tris]
        self.assertTrue(all(nz < 0 for nz in normals) or all(nz > 0 for nz in normals))  # consistent winding
        fan = [(0, 0, 0), (1, 0, 0), (1, 1, 0), (0, 1, 0)]
        self.assertAlmostEqual(area2d(fz.triangulate_patches([(fz.TRIANGLE_FAN, fan)]), (0, 1)), 1.0)
        tri6 = [(0, 0, 0), (1, 0, 0), (0, 1, 0), (2, 0, 0), (3, 0, 0), (2, 1, 0)]
        self.assertEqual(len(fz.triangulate_patches([(fz.TRIANGLES, tri6)])), 2)
        ring = [(0, 0, 0), (0, 0, 4), (4, 0, 4), (4, 0, 0), (0, 0, 0)]
        hole = [(1, 0, 1), (1, 0, 2), (2, 0, 2), (2, 0, 1), (1, 0, 1)]
        for outer_t, inner_t in ((fz.OUTER_RING, fz.INNER_RING), (fz.FIRST_RING, fz.RING)):
            t = fz.triangulate_patches([(outer_t, ring), (inner_t, hole)])
            self.assertAlmostEqual(area2d(t), 15.0)

    def test_keyhole_ring(self):
        """build_env.keyhole: one ring whose shoelace area is outer minus holes and whose even-odd interior
        excludes the hole (what core.js pointInPoly and the voxeliser see)."""
        k = be.keyhole([(0, 0), (10, 0), (10, 10), (0, 10)], [[(3, 3), (6, 3), (6, 6), (3, 6)]])
        self.assertAlmostEqual(abs(ring_area(k)), 91.0)
        self.assertTrue(be.point_in_ring(1, 1, k))
        self.assertFalse(be.point_in_ring(4.5, 4.5, k))


# ------------------------------------------------------------------ 5. env.json and lod2.bin schema
@unittest.skipUnless(ENV.exists(), "src/data/env.json not built")
class TestEnvSchema(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.raw = ENV.read_bytes()
        cls.env = json.loads(cls.raw)

    def test_keys_and_size(self):
        for k in ("meta", "buildings", "roads", "tram", "rail", "trees", "green", "water", "paved", "heating",
                  "pois", "labels", "station", "morph"):
            self.assertIn(k, self.env)
        self.assertLess(len(self.raw), 1.5e6, "architecture §4.1 target")
        m = self.env["meta"]
        self.assertEqual(m["frame"]["kx"], SITE["frame"]["kx"])
        for s in ("zg3d", "osm", "dtm"):
            self.assertIn("fetched", m["sources"][s])
        self.assertGreater(m["sources"]["zg3d"]["parts"], 3000)
        self.assertTrue(any("OpenStreetMap" in a for a in m["attribution"]))
        self.assertTrue(any("ZG3D" in a for a in m["attribution"]))

    def assert_ring(self, p, what):
        self.assertGreaterEqual(len(p), 3, what)
        self.assertNotEqual(p[0], p[-1], what + ": repeated end point")
        for x, z in p:
            self.assertLessEqual(abs(x), 900, what)
            self.assertLessEqual(abs(z), 900, what)
            self.assertAlmostEqual(x * 10, round(x * 10), places=6, msg=what + ": 0.1 m rounding")

    def test_buildings(self):
        ids = set()
        for b in self.env["buildings"]:
            self.assert_ring(b["p"], b["id"])
            self.assertGreaterEqual(b["b"], 0)
            self.assertGreaterEqual(b["h"], 1.0)
            self.assertGreater(b["h"], b["b"])
            self.assertTrue(b["b"] == 0 or b["b"] >= 1.0, "bases below 1 m are 0")
            self.assertIn(b["k"], ("zg3d", "osm"))
            self.assertIsInstance(b["s"], int)
            self.assertTrue(b["id"].startswith(b["k"] + ":"))
            self.assertEqual(b["s"] == 0, b["k"] == "osm")
            self.assertNotIn(b["id"], ids)
            ids.add(b["id"])
            self.assertNotEqual(b["id"], f"osm:w{SITE['station']['osm_way']}", "container excluded")
        years = {b["s"] for b in self.env["buildings"] if b["k"] == "zg3d"}
        self.assertTrue({2008, 2019, 2022} <= years)

    def test_roads(self):
        groups = set()
        for r in self.env["roads"]:
            self.assertGreaterEqual(len(r["p"]), 2)
            self.assertIn(r["c"], range(6))
            self.assertIn(r["o"], (-1, 0, 1))
            self.assertIsInstance(r["l"], int)
            self.assertGreater(r["w"], 0)
            self.assertIn(r["g"], ("A", "B", "C", None))
            self.assertEqual(r["g"] is None, r["c"] == 5)
            self.assertEqual(r["aadt"] > 0, r["g"] is not None)
            if r["g"] == "A":
                self.assertEqual(r["n"], "Ulica grada Vukovara")
            if r["g"] == "B":
                self.assertIn(r["n"], be.NAMES_B)
            if r["c"] < 5 and not (abs(r["p"][0][1]) <= 40 and r["n"] == "Miramarska cesta"):
                self.assertAlmostEqual(r["w"], round(r["l"] * be.LANE_W, 1), places=6)
            groups.add(r["g"])
        self.assertEqual(groups, {"A", "B", "C", None})

    def test_miramarska_override(self):
        ov = [r for r in self.env["roads"] if r["g"] == "B" and len(r["p"]) == 2 and abs(r["p"][0][1]) == 40 and abs(r["p"][1][1]) == 40]
        self.assertEqual(len(ov), 2)
        sb = next(r for r in ov if r["p"][1][1] > r["p"][0][1])            # drawn towards +z = southbound
        nb = next(r for r in ov if r["p"][1][1] < r["p"][0][1])
        self.assertEqual((sb["p"][0][0], sb["w"], sb["l"], sb["o"], sb["aadt"]), (18.8, 13.5, 4, 1, 12000))
        self.assertEqual((nb["p"][0][0], nb["w"], nb["l"], nb["o"], nb["aadt"]), (30.2, 7.5, 2, 1, 8000))
        for r in self.env["roads"]:                                         # no other Miramarska geometry in the band
            if r["g"] == "B" and r not in ov:
                for x, z in r["p"][1:-1]:
                    self.assertFalse(5 < x < 45 and abs(z) < 39.9, r)

    def test_trees_station_morph(self):
        kinds = {t["k"] for t in self.env["trees"]}
        self.assertTrue({"osm", "station"} <= kinds)
        st = [t for t in self.env["trees"] if t["k"] == "station"]
        self.assertEqual(st, [{"x": -5.0, "z": -10.0, "h": 14.0, "r": 9.0, "k": "station"}])
        s = self.env["station"]
        self.assertEqual((s["x"], s["z"], s["inlet"]), (0, 0, 4.0))
        self.assertGreaterEqual(len(s["container"]), 3)
        self.assertEqual(s["tree"], {"x": -5.0, "z": -10.0, "h": 14.0, "r": 9.0})
        m = self.env["morph"]
        for k in ("lambda_p", "lambda_f", "Hbar", "d", "z0"):
            self.assertGreater(m[k], 0)
        self.assertEqual([x["from"] for x in m["sectors"]], list(range(0, 360, 45)))
        # critic §1.10 (500 m disc): lambda_p 0.246, lambda_f 0.193, Hbar 14.2, d 6.8, z0 1.47
        self.assertAlmostEqual(m["lambda_p"], 0.246, delta=0.02)
        self.assertAlmostEqual(m["lambda_f"], 0.193, delta=0.02)
        self.assertAlmostEqual(m["Hbar"], 14.2, delta=1.0)
        self.assertAlmostEqual(m["d"], 6.8, delta=0.7)
        self.assertAlmostEqual(m["z0"], 1.47, delta=0.2)

    def test_layers(self):
        for key in ("green", "water", "paved"):
            for p in self.env[key]:
                self.assert_ring(p, key)
        for h in self.env["heating"]:
            self.assert_ring(h["p"], "heating")
            self.assertGreater(h["w"], 0)
            self.assertLessEqual(h["w"], be.HEAT_W_MAX)
        for poly in self.env["tram"] + self.env["rail"]:
            self.assertGreaterEqual(len(poly), 2)
        for p in self.env["pois"]:
            self.assertIn(p["t"], ("school", "kindergarten", "hospital", "fuel"))
        for lab in self.env["labels"]:
            self.assertIn(lab["k"], ("road", "poi", "park", "water"))
        names = {lab["t"] for lab in self.env["labels"]}
        self.assertTrue({"Vukovarska", "Miramarska", "Park Drage Galića", "Lisinski"} <= names)

    @unittest.skipUnless(LOD2.exists(), "src/data/lod2.bin not built")
    def test_lod2_bin(self):
        data = LOD2.read_bytes()
        magic, ver, n, zero = struct.unpack_from("<4sIII", data, 0)
        self.assertEqual((magic, ver, zero), (b"ZL2B", 1, 0))
        self.assertEqual(len(data), 16 + n * 18 + n + (-(16 + n * 19) % 4))
        self.assertEqual(len(data) % 4, 0)
        self.assertLess(len(data), 2.7e6, "about 2.5 MB budget (architecture §4.1)")
        pos = struct.unpack_from("<%dh" % (9 * n), data, 16)
        cls = data[16 + 18 * n:16 + 19 * n]
        ys = pos[1::3]
        self.assertGreaterEqual(min(ys), 0)                                  # decimetres above ground
        self.assertLess(max(ys), 1200)                                       # < 120 m (tallest ~98 m)
        xs, zs = pos[0::3], pos[2::3]
        self.assertLess(max(math.hypot(x, z) for x, z in zip(xs[::97], zs[::97])), 6000)   # ~500 m radius + a part
        self.assertTrue(set(cls) <= {0, 8, 19, 22})


# ------------------------------------------------------------------ 6. rules
def tags(**kw):
    return {k.replace("__", ":"): v for k, v in kw.items()}


class TestRoadRules(unittest.TestCase):
    def test_class(self):
        self.assertEqual(be.road_class(tags(highway="primary")), 0)
        self.assertEqual(be.road_class(tags(highway="secondary_link")), 1)
        self.assertEqual(be.road_class(tags(highway="tertiary")), 2)
        self.assertEqual(be.road_class(tags(highway="living_street")), 3)
        self.assertEqual(be.road_class(tags(highway="service")), 4)
        self.assertEqual(be.road_class(tags(highway="footway")), 5)
        self.assertIsNone(be.road_class(tags(highway="pedestrian", area="yes")))
        self.assertIsNone(be.road_class(tags(highway="construction")))
        self.assertIsNone(be.road_class({}))

    def test_oneway_lanes(self):
        self.assertEqual(be.road_oneway(tags(oneway="yes")), 1)
        self.assertEqual(be.road_oneway(tags(oneway="-1")), -1)
        self.assertEqual(be.road_oneway(tags(junction="roundabout")), 1)
        self.assertEqual(be.road_oneway(tags(oneway="no")), 0)
        self.assertEqual(be.road_lanes(tags(lanes="3"), 1, 1), 3)
        self.assertEqual(be.road_lanes(tags(lanes="2;3"), 1, 0), 3)
        self.assertEqual(be.road_lanes({}, 1, 0), 4)
        self.assertEqual(be.road_lanes({}, 1, 1), 2)
        self.assertEqual(be.road_lanes({}, 3, 0), 2)
        self.assertEqual(be.road_lanes({}, 5, 0), 0)

    def test_groups(self):
        self.assertEqual(be.road_group("Ulica grada Vukovara", 1), "A")
        self.assertEqual(be.road_group("Miramarska cesta", 2), "B")
        self.assertEqual(be.road_group("Miramarski podvožnjak", 2), "B")
        self.assertEqual(be.road_group("Savska cesta", 1), "C")
        self.assertEqual(be.road_group("", 4), "C")
        self.assertIsNone(be.road_group("Ulica grada Vukovara", 5))

    def test_aadt(self):
        vuk = tags(highway="secondary", name="Ulica grada Vukovara")
        self.assertEqual(be.road_aadt(vuk, 1, 1, (-100, 45), (-1, 0)), 23500)     # W leg, one carriageway
        self.assertEqual(be.road_aadt(vuk, 1, 1, (100, 60), (1, 0)), 22500)       # E leg
        self.assertEqual(be.road_aadt(vuk, 1, 0, (-100, 50), (1, 0)), 47000)      # two-way way: whole link
        mir = tags(highway="tertiary", name="Miramarska cesta")
        self.assertEqual(be.road_aadt(mir, 2, 1, (20, -100), (0, 1)), 12000)      # N leg southbound 60 %
        self.assertEqual(be.road_aadt(mir, 2, 1, (25, -100), (0, -1)), 8000)      # N leg northbound 40 %
        self.assertEqual(be.road_aadt(mir, 2, -1, (25, -100), (0, 1)), 8000)      # oneway=-1 drawn south = NB
        self.assertEqual(be.road_aadt(mir, 2, 0, (30, -50), (0, 1)), 20000)       # joint two-way section
        self.assertEqual(be.road_aadt(mir, 2, 0, (32, 110), (0, 1)), 12000)      # S leg
        self.assertEqual(be.road_aadt(tags(highway="unclassified", name="Trg Stjepana Radića"), 3, 0, (100, -44), (1, 0)), 4000)
        self.assertEqual(be.road_aadt(tags(highway="secondary", name="Ulica Hrvatske bratske zajednice"), 1, 1, (400, 0), (0, 1)), 25000)
        self.assertEqual(be.road_aadt(tags(highway="tertiary"), 2, 0, (0, 0), (1, 0)), 12000)
        self.assertEqual(be.road_aadt(tags(highway="residential"), 3, 0, (0, 0), (1, 0)), 1000)
        self.assertEqual(be.road_aadt(tags(highway="service"), 4, 0, (0, 0), (1, 0)), 150)
        self.assertEqual(be.road_aadt(tags(highway="secondary_link", name="Slavonska avenija"), 1, 1, (0, 600), (1, 0)), 6250)
        self.assertEqual(be.road_aadt(tags(highway="footway"), 5, 0, (0, 0), (1, 0)), 0)

    def test_make_road_width(self):
        r = be.make_road([(0, 0), (10, 0)], tags(highway="secondary", lanes="3", oneway="yes", name="Savska cesta"), 1, 1)
        self.assertEqual((r["l"], r["w"], r["g"], r["aadt"]), (3, 9.8, "C", 22500))
        r = be.make_road([(0, 0), (10, 0)], tags(highway="footway"), 5, 0)
        self.assertEqual((r["g"], r["aadt"], r["w"]), (None, 0, 2))

    def test_override(self):
        ov = be.miramarska_override()
        self.assertEqual([r["p"] for r in ov], [[[18.8, -40], [18.8, 40]], [[30.2, 40], [30.2, -40]]])
        self.assertEqual([r["aadt"] for r in ov], [12000, 8000])
        self.assertEqual([r["w"] for r in ov], [13.5, 7.5])

    def test_overpass_fallback(self):
        calls = []

        def fake_get(url, **kw):
            calls.append(url)
            if url == SITE["overpass"][0]:
                raise fo.urllib.error.URLError("down")
            return json.dumps({"osm3s": {"timestamp_osm_base": "2026-09-27T00:00:00Z"}, "elements": []}).encode()

        orig = fo.get
        fo.get = fake_get
        try:
            d, url = fo.overpass("[out:json];node(1);out;")
        finally:
            fo.get = orig
        self.assertEqual(url, SITE["overpass"][1])
        self.assertEqual(calls, SITE["overpass"][:2])
        self.assertEqual(d["elements"], [])
        self.assertIn("way(1409603653)", fo.queries(750)["station"])


class TestBuildingRules(unittest.TestCase):
    def test_osm_heights(self):
        self.assertEqual(be.osm_building_height(tags(building="yes", building__levels="4"), 300)[:2], (17.5, 0.0))
        self.assertEqual(be.osm_building_height(tags(building="yes", height="21 m"), 300)[:2], (21.0, 0.0))
        self.assertEqual(be.osm_building_height(tags(building="house"), 120)[:2], (7.0, 0.0))
        self.assertEqual(be.osm_building_height(tags(building="retail"), 13)[:2], (3.0, 0.0))    # kiosk
        self.assertEqual(be.osm_building_height(tags(building="yes"), 500)[:2], (14.3, 0.0))
        h, b, _ = be.osm_building_height(tags(building="roof", building__levels="1"), 40)
        self.assertEqual((h, b), (5.0, 4.0))                                                    # canopy slab
        self.assertEqual(be.osm_building_height(tags(building="yes", min_height="4", height="10"), 200)[:2], (10.0, 4.0))

    def test_macdonald_reproduces_critic(self):
        d, z0 = be.macdonald(0.246, 0.193, 14.2)          # critic §1.10: d 6.8 m, z0 1.47 m
        self.assertAlmostEqual(d, 6.8, delta=0.05)
        self.assertAlmostEqual(z0, 1.47, delta=0.03)
        d, z0 = be.macdonald(0.22, 0.17, 12.8)            # sector N: d 5.6, z0 1.35
        self.assertAlmostEqual(d, 5.6, delta=0.1)
        self.assertAlmostEqual(z0, 1.35, delta=0.05)

    def test_region_stats_synthetic(self):
        """A single 10 m x 10 m x 20 m block: lambda_p, Hbar and lambda_f by hand."""
        g = be.Grid(30.0, 1.0)
        H = be.paint_heights(g, [{"p": [(-5, -5), (5, -5), (5, 5), (-5, 5)], "h": 20.0}])
        s = be.region_stats(g, H, 0.0, "disc", 20.0)
        area = s["cells"]
        self.assertAlmostEqual(s["lambda_p"], 100 / area, delta=0.01)
        self.assertAlmostEqual(s["Hbar"], 20.0)
        self.assertAlmostEqual(s["lambda_f"], 10 * 20 / area, delta=0.01)
        s45 = be.region_stats(g, H, 45.0, "disc", 20.0)
        self.assertAlmostEqual(s45["lambda_f"] / s["lambda_f"], math.sqrt(2), delta=0.12)

    def test_helpers(self):
        pieces = be.clip_polyline_box([(-10, 0), (10, 0)], -5, 5, -5, 5)
        self.assertEqual(len(pieces), 1)
        self.assertAlmostEqual(be.polyline_length(pieces[0]), 10.0)
        out = be.clip_polyline_box([(-10, 0), (10, 0)], -5, 5, -5, 5, keep_inside=False)
        self.assertEqual(len(out), 2)
        self.assertAlmostEqual(sum(be.polyline_length(p) for p in out), 10.0)
        self.assertEqual(be.r1(3.04), 3)
        self.assertEqual(be.r1(3.06), 3.1)
        self.assertEqual(be.parse_float("12,5 m"), 12.5)
        self.assertIsNone(be.parse_float("tall"))
        clip = be.clip_ring_to_box([(0, 0), (10, 0), (10, 10), (0, 10)], 5, 5, 20, 20)
        self.assertAlmostEqual(abs(ring_area(clip)), 25.0)
        g = be.Grid(10.0, 1.0)
        m = be.paint_mask(g, [[(-3, -3), (3, -3), (3, 3), (-3, 3)]])
        self.assertEqual(sum(m), 36)

    def test_frame_round_trip(self):
        for x, z in ((0, 0), (750, -750), (-321.4, 55.5)):
            X, Z = xz(*latlon(x, z))
            self.assertAlmostEqual(X, x, places=6)
            self.assertAlmostEqual(Z, z, places=6)


if __name__ == "__main__":
    if "--regen" in sys.argv:
        (FIX / "geo_tiny_dtm.tif").write_bytes(tiny_tiff())
        print("wrote", FIX / "geo_tiny_dtm.tif")
    else:
        unittest.main()
