"""Tests of tools/aqmodel.py (the Python mirror of the JS model layer) and of tools/calibrate.py helpers [owner: models].

    python3 -m unittest tests/python/test_aqmodel.py -v

No network. Inputs are the saved parity vectors (tests/python/fixtures/parity_vectors.json, generated by
`python3 tools/aqmodel.py --write-parity`), synthetic geometry, and, where noted, the committed processed tables in
data/processed (skipped when absent).
"""
from __future__ import annotations

import datetime as dt
import gzip
import json
import math
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools"))

import aqmodel as M  # noqa: E402
import calibrate as CAL  # noqa: E402

FIX = ROOT / "tests" / "python" / "fixtures" / "parity_vectors.json"
JS_TEST = ROOT / "src" / "js" / "tests" / "models.test.js"
PROCESSED = ROOT / "data" / "processed"


def dec(v):
    """Undo the JSON encoding of ±Infinity / NaN used in the parity file."""
    if v == "Infinity":
        return math.inf
    if v == "-Infinity":
        return -math.inf
    if v == "NaN":
        return math.nan
    if isinstance(v, list):
        return [dec(x) for x in v]
    if isinstance(v, dict):
        return {k: dec(x) for k, x in v.items()}
    return v


def close(tc: unittest.TestCase, a, b, path: str = "", rel: float = 1e-6) -> None:
    """Deep comparison with the tolerance of models.test.js (1e-6 relative + 1e-12 absolute)."""
    if isinstance(b, bool) or b is None or isinstance(b, str):
        tc.assertEqual(a, b, path)
    elif isinstance(b, (int, float)):
        if math.isnan(b):
            tc.assertTrue(math.isnan(a), f"{path}: expected NaN, got {a}")
        elif math.isinf(b):
            tc.assertEqual(a, b, path)
        else:
            tc.assertLessEqual(abs(a - b), rel * abs(b) + 1e-12, f"{path}: {a} vs {b}")
    elif isinstance(b, list):
        tc.assertEqual(len(a), len(b), f"{path}: length")
        for i, (x, y) in enumerate(zip(a, b)):
            close(tc, x, y, f"{path}[{i}]", rel)
    elif isinstance(b, dict):
        for k in b:
            close(tc, a[k], b[k], f"{path}.{k}", rel)
    else:  # pragma: no cover
        tc.fail(f"{path}: unsupported type {type(b)}")


# Python counterparts of MT_RUN in models.test.js
RUN = {
    "local_parts": lambda i: M.local_parts(i["t"]),
    "solar_elevation": lambda i: M.solar_elevation(i["t"]),
    "stability_class": lambda i: M.stability_class(i["u10"], i["sw"], i["cloud"], i["t"]),
    "obukhov_length": lambda i: M.obukhov_length(i["cls"], i["z0"]),
    "mixing_height": lambda i: M.mixing_height(i["cls"], i["blh"], i["mode"], i["hMin"]),
    "u_eff": lambda i: M.u_eff(i["u10"], i["U0"]),
    "direction_weights": lambda i: M.direction_weights(i["dir"], i["u10"]),
    "turb_params": lambda i: M.turb_params(i["cls"], i["z0"], i["d"], i["Hbar"], i["h_eff"]),
    "most": lambda i: {"psiM": M.psi_m, "phiH": M.phi_h}[i["fn"]](i["x"]) if "turb" not in i
    else {"kHatMO": M.k_hat_mo, "uHat": M.u_hat}[i["fn"]](i["x"], i["turb"]),
    "j_no2": lambda i: M.j_no2(i["sw"]),
    "k_no_o3": lambda i: M.k_no_o3(i["t"]),
    "vector_mean_wind": lambda i: M.vector_mean_wind(i["list"]),
    "no2_chemistry": lambda i: M.no2_chemistry(i["noxInc"], i["no2Bg"], i["noxBg"], i["o3Bg"], i["tau"], i["J"], i["k"], i["fNO2"]),
    "ppb": lambda i: M.PPB[i["p"]],
    "eaqi": lambda i: M.eaqi(i["p"], i["v"], i["scheme"]),
    "traffic_factor": lambda i: M.traffic_factor(i["t"], i["month"]),
    "measure_factors": lambda i: M.measure_factors(i["m"]),
    "group_strengths": lambda i: M.group_strengths(i["p"], i["t"], i["m"], i["heating"], None, 1.0, i["congestionShare"]),
    "increment": lambda i: M.increment(i["gamma"], i["age"], i["q"], i["u10"], i["beta"], i["U0"]),
    "metrics": lambda i: M.metrics(i["obs"], i["mod"]),
    "mqi": lambda i: M.mqi(i["obs"], i["mod"], i["p"]),
    "chem_sample": lambda i: M.no2_chemistry(i["noxInc"], i["no2Bg"], i["noxBg"], i["o3Bg"], i["tau"], M.j_no2(i["sw"]),
                                             M.k_no_o3(i["t2"]), i["fNO2"]),
}


class TestParityVectors(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.raw = json.loads(FIX.read_text(encoding="utf-8"))
        cls.cases = dec(cls.raw["cases"])

    def test_embedded_copy_in_models_test_js_is_identical(self):
        js = JS_TEST.read_text(encoding="utf-8")
        a = js.index("const MT_PARITY = ") + len("const MT_PARITY = ")
        b = js.index(M.PARITY_END)
        body = js[a:b].rstrip().rstrip(";")
        self.assertEqual(json.loads(body), self.raw, "run python3 tools/aqmodel.py --write-parity")

    def test_every_section_has_a_runner(self):
        for sec in self.cases:
            if not sec.startswith("fallback"):
                self.assertIn(sec, RUN, sec)

    def test_sections_reproduce(self):
        n = 0
        for sec, cases in self.cases.items():
            if sec.startswith("fallback"):
                continue
            for k, c in enumerate(cases):
                close(self, RUN[sec](c["in"]), c["out"], f"{sec}#{k}")
                n += 1
        self.assertGreater(n, 900)

    def test_fallback_reproduces(self):
        env = self.cases["fallback_env"][0]["in"]["env"]
        fb = M.FallbackModel(env)
        close(self, {"center": list(fb.center), "n": fb.src["n"], "canyons": fb.canyons}, self.cases["fallback_env"][0]["out"], "env")
        for k, c in enumerate(self.cases["fallback_receptor"]):
            close(self, fb.receptor(c["in"]["dir"], c["in"]["cls"]), c["out"], f"receptor#{k}")
        for k, c in enumerate(self.cases["fallback_slice"]):
            close(self, fb.slice(c["in"]["dir"], c["in"]["cls"], c["in"]["height"], c["in"]["grid"]), c["out"], f"slice#{k}")


class TestMeteo(unittest.TestCase):
    def test_kernel_sums_to_one_and_calm_is_uniform(self):
        for u in (0.5, 1.0, 2.0, 6.0):
            for d in (0, 33, 180, 359.5):
                w = M.direction_weights(d, u)
                self.assertAlmostEqual(sum(w), 1.0, places=12)
                self.assertLessEqual(abs(M.ang_diff(M.DIRS16[w.index(max(w))], d)), 11.25 + 1e-9)
        self.assertEqual(M.direction_weights(10, 0.49), [1 / 16] * 16)
        w = M.direction_weights(90, 3)
        self.assertAlmostEqual(w[5] / w[4], math.exp(-0.5), places=12)

    def test_stability_tables(self):
        self.assertEqual(M.stability_class(1, 950, 50), "A")
        self.assertEqual(M.stability_class(4, 950, 50), "B")
        self.assertEqual(M.stability_class(7, 950, 50), "C")
        self.assertEqual(M.stability_class(2.5, 700, 50), "B")
        self.assertEqual(M.stability_class(4, 300, 50), "C")
        self.assertEqual(M.stability_class(1, 100, 50), "D")
        self.assertEqual(M.stability_class(1, 0, 30), "F")
        self.assertEqual(M.stability_class(4, 0, 30), "E")
        self.assertEqual(M.stability_class(2.5, 0, 70), "E")
        self.assertEqual(M.stability_class(4, 0, 70), "D")
        self.assertEqual(M.stability_class(1, 0, 100), "D")
        for c, L in {"A": -9.6, "B": -22, "C": -135, "E": 106, "F": 22}.items():   # critic §1.13
            self.assertAlmostEqual(M.obukhov_length(c, 0.5), L, delta=abs(L) * 0.03)
        self.assertEqual(M.obukhov_length("D"), math.inf)
        self.assertAlmostEqual(M.turb_params("D", 1.4, 8, 14)["ustar_hat"], 0.162, delta=0.001)   # physics §6.2

    def test_local_time_matches_zoneinfo(self):
        try:
            from zoneinfo import ZoneInfo
            tz = ZoneInfo("Europe/Zagreb")
        except Exception:  # pragma: no cover - tzdata not installed
            self.skipTest("zoneinfo/tzdata not available")
        t = dt.datetime(2024, 1, 1, tzinfo=dt.timezone.utc)
        while t < dt.datetime(2026, 1, 1, tzinfo=dt.timezone.utc):
            p = M.local_parts(t.timestamp() * 1000)
            ref = (t - dt.timedelta(hours=1)).astimezone(tz)
            self.assertEqual((p["year"], p["month"], p["day"], p["hour"], p["dow"]),
                             (ref.year, ref.month, ref.day, ref.hour, ref.weekday()), t.isoformat())
            t += dt.timedelta(hours=7)

    def test_solar_elevation(self):
        self.assertAlmostEqual(M.solar_elevation("2025-03-20T11:04:00Z"), 90 - 45.8, delta=0.6)
        self.assertAlmostEqual(M.solar_elevation("2025-06-21T11:02:00Z"), 90 - 45.8 + 23.44, delta=0.6)
        self.assertLess(M.solar_elevation("2025-06-21T23:00:00Z"), 0)


class TestChemistry(unittest.TestCase):
    def test_limits(self):
        k, J = M.k_no_o3(15), M.j_no2(600)
        r = M.no2_chemistry(0, 0, 0, 50, 60, J, k)
        self.assertAlmostEqual(r["no2"], 0, places=9)
        self.assertAlmostEqual(r["o3"], 50, places=9)
        r = M.no2_chemistry(500, 20, 50, 10, math.inf, 0, k, 0.1)             # O3-limited titration
        X = 10 / M.PPB["o3"] + 20 / M.PPB["no2"] + 50 / M.PPB["no2"]
        self.assertAlmostEqual(r["no2"], X * M.PPB["no2"], places=9)
        self.assertAlmostEqual(r["o3"], 0, places=9)
        r = M.no2_chemistry(120, 25, 40, 45, math.inf, J, k)                  # PSS: k (N-x)(X-x) = J x
        N, x = r["nox"] / M.PPB["no2"], r["no2"] / M.PPB["no2"]
        self.assertAlmostEqual(k * (N - x) * (r["ox"] - x), J * x, delta=1e-9 * J * x)
        self.assertAlmostEqual(M.k_no_o3(15), 4.19e-4, delta=0.02e-4)         # critic §1.13
        self.assertAlmostEqual(M.j_no2(800) / 1.05, 8.7e-3, delta=0.05e-3)
        self.assertAlmostEqual(M.PPB["no2"], 1.9125, places=4)

    def test_rmse_on_the_2025_sample(self):
        cases = dec(json.loads(FIX.read_text(encoding="utf-8"))["cases"]).get("chem_sample") or []
        if len(cases) < 250:
            self.skipTest("chem_sample empty (processed tables were absent when the vectors were generated)")
        obs = [c["in"]["obs"] for c in cases]
        mod = [RUN["chem_sample"](c["in"])["no2"] for c in cases]
        m = M.metrics(obs, mod)
        self.assertLess(m["RMSE"], 6.5)       # critic §1.2: 5.0 on all 2025 hours
        self.assertGreater(m["R"], 0.94)
        self.assertLess(abs(m["FB"]), 0.05)

    @unittest.skipUnless((PROCESSED / "iszz_hourly.csv.gz").exists() and (PROCESSED / "ifs_hourly.csv.gz").exists(),
                         "processed tables not present")
    def test_rmse_on_all_2025_hours(self):
        obs, met = CAL.load_processed(PROCESSED / "iszz_hourly.csv.gz", PROCESSED / "ifs_hourly.csv.gz",
                                      "2025-01-01T01:00:00Z", "2026-01-01T00:00:00Z")
        o, p = [], []
        for t, v in obs.items():
            m = met.get(t)
            if not m or not all(k in v and math.isfinite(v[k]) for k in ("z1.nox", "z1.no2", "z4.nox", "z4.no2", "z4.o3")):
                continue
            if not (math.isfinite(m["sw"]) and math.isfinite(m["t2"])):
                continue
            r = M.no2_chemistry(v["z1.nox"] - v["z4.nox"], v["z4.no2"], v["z4.nox"], v["z4.o3"], 60, M.j_no2(m["sw"]),
                                M.k_no_o3(m["t2"]), 0.10)
            o.append(v["z1.no2"])
            p.append(r["no2"])
        mm = M.metrics(o, p)
        self.assertGreater(mm["n"], 7000)
        self.assertAlmostEqual(mm["RMSE"], 5.0, delta=0.4)     # critic §1.2: 5.0; this data: 5.1
        self.assertGreater(mm["R"], 0.955)


class TestEmissions(unittest.TestCase):
    def test_weekly_mean_is_one(self):
        t0 = dt.datetime(2025, 3, 10, tzinfo=dt.timezone.utc).timestamp() * 1000
        s = sum(M.traffic_factor(t0 + h * 3600e3, month=False) for h in range(168))
        self.assertAlmostEqual(s / 168, 1.0, places=12)
        for k in ("weekday", "saturday", "sunday"):
            self.assertAlmostEqual(sum(M.TRAFFIC_PROFILES["hour"][k]), 1.0, places=12)

    def test_units_and_measures(self):
        t = "2025-03-11T08:00:00Z"
        f = M.traffic_factor(t)
        q = M.group_strengths("nox", t)
        self.assertAlmostEqual(q["A"], 10000 * f / 24 * 0.5 / 3.6e6, delta=1e-18)
        self.assertEqual(q["D"], 0.0)
        self.assertAlmostEqual(M.group_strengths("nox", "2025-01-15T19:00:00Z", heating="auto")["D"], 1e-6, delta=1e-18)
        self.assertEqual(M.group_strengths("nox", "2025-07-15T19:00:00Z", heating="auto")["D"], 0.0)
        self.assertEqual(M.group_strengths("nox", t, {"carFreeMiramarska": True})["B"], 0.0)
        self.assertAlmostEqual(M.group_strengths("nox", t, {"lez": True})["A"], 0.6 * q["A"], delta=1e-18)
        self.assertEqual(M.group_strengths("nox", t, {"evShare": 100})["A"], 0.0)
        self.assertGreater(M.group_strengths("pm10", t, {"evShare": 100})["A"], 0.0)
        self.assertEqual(M.easter(2025), (4, 20))
        self.assertEqual(M.easter(2026), (4, 5))
        self.assertTrue(M.is_holiday(2026, 6, 4))    # Corpus Christi 2026 = Easter + 60
        self.assertTrue(M.is_holiday(2025, 4, 21))   # Easter Monday 2025


class TestMetrics(unittest.TestCase):
    def test_known_vectors(self):
        m = M.metrics([1, 2, 3, 4], [2, 2, 3, 8])
        self.assertAlmostEqual(m["FB"], -0.4, places=12)
        self.assertAlmostEqual(m["NMSE"], 4.25 / 9.375, places=12)
        self.assertAlmostEqual(m["MG"], math.sqrt(0.5), places=12)
        self.assertAlmostEqual(m["VG"], math.exp(2 * math.log(0.5) ** 2 / 4), places=12)
        self.assertAlmostEqual(m["FAC2"], 1.0, places=12)
        self.assertAlmostEqual(m["NAD"], 0.2, places=12)
        self.assertAlmostEqual(m["R"], 9.5 / math.sqrt(5 * 24.75), places=12)
        p = M.metrics([5, 10, 20, math.nan], [5, 10, 20, 7])
        self.assertEqual((p["n"], p["FB"], p["NMSE"], p["MG"], p["VG"], p["FAC2"]), (3, 0.0, 0.0, 1.0, 1.0, 1.0))
        self.assertAlmostEqual(M.metrics([0.2, -3, 50], [0.5, 0.1, 150])["FAC2"], 2 / 3, places=12)


class TestFallback(unittest.TestCase):
    def test_long_crosswind_road_matches_the_line_source_formula(self):
        """A 4 km road perpendicular to the wind: Σ point sources = W/(√(2π) σz) · (vertical terms), class D."""
        env = {"roads": [{"p": [[-2000, 50], [2000, 50]], "g": "A", "aadt": 10000, "o": 0, "w": 0.001}], "buildings": []}
        fb = M.FallbackModel(env, radius=3000)
        g = fb.receptor(180, "D")["gamma"][0]        # wind from the south: the road is 50 m upwind of the receptor
        x = 50.0
        _, szb = M.briggs("D", x)
        sz = math.sqrt(M.FB_SZ0 ** 2 + szb ** 2)
        zr, hs = M.RECEPTOR[1], M.FB_HS_ROAD
        V = math.exp(-(zr - hs) ** 2 / (2 * sz * sz)) + math.exp(-(zr + hs) ** 2 / (2 * sz * sz))
        self.assertAlmostEqual(g, V / (math.sqrt(2 * math.pi) * sz), delta=0.01 * g)

    def test_linear_in_aadt_and_zero_upwind(self):
        env = {"roads": [{"p": [[-300, 40], [300, 40]], "g": "A", "aadt": 20000, "w": 10}], "buildings": []}
        a = M.FallbackModel(env).receptor(200, "D")["gamma"][0]
        env["roads"][0]["aadt"] = 40000
        b = M.FallbackModel(env).receptor(200, "D")["gamma"][0]
        self.assertAlmostEqual(b, 2 * a, delta=1e-12)
        self.assertEqual(M.FallbackModel(env).receptor(0, "D")["gamma"][0], 0.0)   # wind from N: road downwind

    def test_canyon_term(self):
        fb = M.FallbackModel(M.synthetic_env())
        self.assertIsNotNone(fb.canyons[1], "the B street between two slabs is a canyon")
        self.assertIsNone(fb.canyons[0])
        lee = fb.receptor(270, "D")["canyon"][1]     # wind from W: receptor (x=0) on the upwind side of B (x≈20)
        self.assertGreater(lee, 0)
        self.assertEqual(fb.receptor(0, "D")["canyon"][1], 0.0)   # parallel wind: no cross-canyon vortex

    def test_real_env_speed(self):
        path = ROOT / "src" / "data" / "env.json"
        env = json.loads(path.read_text(encoding="utf-8"))
        import time
        t0 = time.perf_counter()
        fb = M.FallbackModel(env)
        r = fb.receptor(45, "D")
        self.assertLess(time.perf_counter() - t0, 30)
        self.assertTrue(all(math.isfinite(v) and v >= 0 for v in r["gamma"]))


class TestCalibrate(unittest.TestCase):
    def _synthetic(self, beta=3.0, U0=1.3, n=600):
        import random
        rnd = random.Random(7)
        hours = []
        for i in range(n):
            u = rnd.uniform(0.2, 5)
            S = rnd.uniform(1e-6, 4e-5)
            hours.append({"S": S, "u": u, "obs": 1e6 * beta * S / math.sqrt(u * u + U0 * U0), "month": 202501 + (i % 12)})
        return hours

    def test_fit_recovers_parameters_with_and_without_numpy(self):
        hours = self._synthetic()
        saved = CAL.np
        try:
            for mod in (saved, None):
                CAL.np = mod
                p = CAL.fit(hours)
                self.assertAlmostEqual(p["beta"], 3.0, delta=0.02)
                self.assertAlmostEqual(p["U0"], 1.3, delta=0.051)
        finally:
            CAL.np = saved

    def test_write_if_changed_is_idempotent(self):
        with tempfile.TemporaryDirectory() as d:
            p = Path(d) / "c.json"
            CAL.write_if_changed(p, {"a": 1.5, "b": [1, 2]})
            first = p.read_text()
            CAL.write_if_changed(p, {"a": 1.5, "b": [1, 2]})
            self.assertEqual(first, p.read_text())
            CAL.write_if_changed(p, {"a": 2.0})
            self.assertEqual(json.loads(p.read_text())["a"], 2.0)

    def test_baseline_on_a_pure_profile(self):
        hours = []
        for i in range(24 * 60):
            h = i % 24
            u = 1 + (i * 7 % 13) / 4
            hours.append({"obs": (10 + h) / math.sqrt(u * u + CAL.BASELINE_U0 ** 2), "u": u, "dir": (i * 37) % 360,
                          "dtype": "weekday", "lhour": h})
        b = CAL.baseline_fit(hours)
        pred = CAL.baseline_predict(b, hours)
        m = M.metrics([h["obs"] for h in hours], pred)
        self.assertLess(m["NMSE"], 1e-9)


if __name__ == "__main__":
    unittest.main()
