#!/usr/bin/env python3
"""Python mirror of the pure model layer: src/js/{meteo,chemistry,emissions,fallback,model}.js [owner: models].

    python3 tools/aqmodel.py --write-parity          # regenerate tests/python/fixtures/parity_vectors.json and the
                                                     # embedded copy in src/js/tests/models.test.js
    python3 tools/aqmodel.py --receptor 45 D         # Gaussian-fallback unit responses at ZAGREB-1 (src/data/env.json)
    python3 tools/aqmodel.py --hour 2025-01-14T08:00Z --u10 1.2 --dir 45 --sw 50 --cc 90 --t2 0

Every function here is a line-by-line port of its JavaScript counterpart (same names in snake_case, same order of
floating-point operations where it matters). The parity vectors are generated from this file and checked by
src/js/tests/models.test.js to 1e-6 relative, so any change to the arithmetic must be made in both languages and the
vectors regenerated. Formulas, constants and their sources are documented once, in the JS files and in
docs/05-emissions.md, docs/06-chemistry.md and docs/07-calibration.md; the comments below only point there.

Standard library only (architecture §3: numpy is optional in calibrate.py only).
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import math
import os
import random
import sys
import tempfile
from pathlib import Path
from typing import Any, Iterable, Sequence

sys.path.insert(0, str(Path(__file__).resolve().parent))
from common import ROOT, SITE, SRC_DATA, log  # noqa: E402

MD: dict = SITE["model_defaults"]
DEG = math.pi / 180
UTC = dt.timezone.utc
RECEPTOR = (0.0, float(SITE["station"]["inlet_height_m"]), 0.0)   # (x, y, z) like RECEPTOR in core.js
PARITY_JSON = ROOT / "tests" / "python" / "fixtures" / "parity_vectors.json"
MODELS_TEST_JS = ROOT / "src" / "js" / "tests" / "models.test.js"
PARITY_BEGIN, PARITY_END = "/* PARITY-BEGIN (generated by tools/aqmodel.py --write-parity; do not edit) */", "/* PARITY-END */"


# ================================================================== core.js helpers
def wrap360(a: float) -> float:
    return ((a % 360) + 360) % 360


def ang_diff(a: float, b: float) -> float:
    d = wrap360(a - b)
    return d - 360 if d > 180 else d


def clamp(x: float, a: float, b: float) -> float:
    return min(b, max(a, x))


def finite(x: Any) -> bool:
    return isinstance(x, (int, float)) and not isinstance(x, bool) and math.isfinite(x)


def point_in_poly(x: float, z: float, poly: Sequence[Sequence[float]]) -> bool:
    inside = False
    j = len(poly) - 1
    for i in range(len(poly)):
        xi, zi = poly[i][0], poly[i][1]
        xj, zj = poly[j][0], poly[j][1]
        if (zi > z) != (zj > z) and x < ((xj - xi) * (z - zi)) / (zj - zi) + xi:
            inside = not inside
        j = i
    return inside


def bounds(poly) -> dict:
    return {"x0": min(p[0] for p in poly), "x1": max(p[0] for p in poly),
            "z0": min(p[1] for p in poly), "z1": max(p[1] for p in poly)}


def seg_dist(x: float, z: float, ax: float, az: float, bx: float, bz: float) -> float:
    dx, dz = bx - ax, bz - az
    L2 = dx * dx + dz * dz or 1e-12
    s = clamp(((x - ax) * dx + (z - az) * dz) / L2, 0, 1)
    return math.hypot(x - ax - dx * s, z - az - dz * s)


def to_ms(t: Any) -> float:
    """Epoch ms from a number, datetime or ISO string ('2025-01-14T08:00Z')."""
    if isinstance(t, (int, float)):
        return float(t)
    if isinstance(t, dt.datetime):
        return (t if t.tzinfo else t.replace(tzinfo=UTC)).timestamp() * 1000
    s = str(t).replace("Z", "+00:00")
    d = dt.datetime.fromisoformat(s)
    return (d if d.tzinfo else d.replace(tzinfo=UTC)).timestamp() * 1000


# ================================================================== meteo.js
DIRS16 = [i * 22.5 for i in range(16)]


def dir_index16(deg: float) -> int:
    if not finite(deg):
        return 0
    # JS Math.round rounds .5 up; floor(x + 0.5) reproduces it for x >= 0
    return int(math.floor(wrap360(deg) / 22.5 + 0.5)) % 16


def _last_sunday_utc(year: int, month: int) -> float:
    """01:00 UTC of the last Sunday of `month` (1..12), epoch ms (met_lastSundayUTC)."""
    nxt = dt.datetime(year + (month == 12), month % 12 + 1, 1, 1, tzinfo=UTC)
    last = nxt - dt.timedelta(days=1)
    back = (last.weekday() + 1) % 7                     # days since Sunday
    return (last - dt.timedelta(days=back)).timestamp() * 1000


def local_parts(t: Any, hour_start: bool = True) -> dict:
    """Europe/Zagreb calendar of the hour start (met_localParts): EU summer-time rule, Directive 2000/84/EC."""
    ms = to_ms(t) - (3600e3 if hour_start else 0)
    y = dt.datetime.fromtimestamp(ms / 1000, tz=UTC).year
    dst = _last_sunday_utc(y, 3) <= ms < _last_sunday_utc(y, 10)
    off = 2 if dst else 1
    d = dt.datetime.fromtimestamp((ms + off * 3600e3) / 1000, tz=UTC)
    return {"year": d.year, "month": d.month, "day": d.day, "hour": d.hour, "dow": d.weekday(), "offset": off}


def solar_elevation(t: Any, lat: float = SITE["station"]["lat"], lon: float = SITE["station"]["lon"]) -> float:
    """NOAA General Solar Position Calculations (Spencer 1971 series), degrees, no refraction."""
    ms = to_ms(t)
    d = dt.datetime.fromtimestamp(ms / 1000, tz=UTC)
    y = d.year
    leap = (y % 4 == 0 and y % 100 != 0) or y % 400 == 0
    doy = math.floor((ms - dt.datetime(y, 1, 1, tzinfo=UTC).timestamp() * 1000) / 86400e3) + 1
    hour = d.hour + d.minute / 60 + d.second / 3600
    g = (2 * math.pi / (366 if leap else 365)) * (doy - 1 + (hour - 12) / 24)
    eqtime = 229.18 * (0.000075 + 0.001868 * math.cos(g) - 0.032077 * math.sin(g)
                       - 0.014615 * math.cos(2 * g) - 0.040849 * math.sin(2 * g))
    decl = (0.006918 - 0.399912 * math.cos(g) + 0.070257 * math.sin(g) - 0.006758 * math.cos(2 * g)
            + 0.000907 * math.sin(2 * g) - 0.002697 * math.cos(3 * g) + 0.00148 * math.sin(3 * g))
    tst = hour * 60 + eqtime + 4 * lon
    ha = (tst / 4 - 180) * DEG
    cz = math.sin(lat * DEG) * math.sin(decl) + math.cos(lat * DEG) * math.cos(decl) * math.cos(ha)
    return 90 - math.acos(clamp(cz, -1, 1)) / DEG


def shortwave_estimate(elev_deg: float, cloud_pct: float | None) -> float:
    """Holtslag & van Ulden (1983) clear-sky irradiance with cloud reduction (met_shortwaveEstimate)."""
    if not (elev_deg > 0):
        return 0.0
    N = clamp((cloud_pct if finite(cloud_pct) else 50) / 100, 0, 1)
    return max(0.0, (990 * math.sin(elev_deg * DEG) - 30) * (1 - 0.75 * math.pow(N, 3.4)))


MET_SRDT = ["AABCC", "ABBCD", "BCCDD", "DDDDD"]
MET_CLASSES = ["A", "B", "C", "D", "E", "F"]
MET_GROUP_CLASS = {"AC": "B", "D": "D", "EF": "F"}
MET_GOLDER = {"A": (-0.096, 0.029), "B": (-0.037, 0.029), "C": (-0.002, 0.018), "D": (0.0, 0.0),
              "E": (0.004, -0.018), "F": (0.035, -0.036)}
MET_BLH_MEDIAN = {"A": 1178, "B": 520, "C": 1060, "D": 135, "E": 278, "F": 30}
MET_H_RAW_FLOOR = 10


def stability_class(u10: float | None, sw: float | None = None, cloud: float | None = None, t: Any = None) -> str:
    """SRDT by day, Turner by night (stabilityClass)."""
    if not finite(u10):
        return "D"
    G = sw
    if not finite(G):
        G = 0.0 if t is None else shortwave_estimate(solar_elevation(to_ms(t) - 1800e3), cloud)
    if G > 0:
        row = 0 if G >= 925 else 1 if G >= 675 else 2 if G >= 175 else 3
        col = 0 if u10 < 2 else 1 if u10 < 3 else 2 if u10 < 5 else 3 if u10 < 6 else 4
        return MET_SRDT[row][col]
    cc = cloud if finite(cloud) else 50
    if cc >= 95:
        return "D"
    if cc > 40:
        return "F" if u10 < 1.9 else "E" if u10 < 3.4 else "D"
    return "F" if u10 < 3.4 else "E" if u10 < 5.5 else "D"


def stability_group(cls: str) -> str:
    if cls in ("AC", "D", "EF"):
        return cls
    return "AC" if cls in ("A", "B", "C") else "EF" if cls in ("E", "F") else "D"


def met_class(c: str) -> str:
    return MET_GROUP_CLASS.get(c) or (c if c in MET_CLASSES else "D")


def obukhov_length(cls: str, z0: float = MD["z0_m"]) -> float:
    a, b = MET_GOLDER[met_class(cls)]
    inv = a + b * math.log10(min(z0, 0.5))
    return math.inf if abs(inv) < 1e-12 else 1 / inv


def mixing_height(cls: str = "D", blh: float | None = None, mode: str = "auto", h_min: float | None = None) -> float:
    base = blh if finite(blh) else MET_BLH_MEDIAN[met_class(cls)]
    m = str(mode)
    floor = (MET_H_RAW_FLOOR if m == "nwp" else 315 if m == "315" else 100 if m == "100"
             else (h_min if finite(h_min) else MD["h_min_m"]))
    return max(base, floor)


def u_eff(u10: float | None, U0: float = MD["U0"]) -> float:
    u = max(0.0, u10) if finite(u10) else 0.0
    return math.sqrt(u * u + U0 * U0)


def direction_weights(from_deg: float | None, u10: float | None, dirs: Sequence[float] = DIRS16) -> list[float]:
    n = len(dirs)
    if not (finite(u10) and u10 >= 0.5) or not finite(from_deg):
        return [1 / n] * n
    s = min(60.0, 22.5 * max(1.0, 2 / u10))
    tmp = []
    for d0 in dirs:
        d = ang_diff(from_deg, d0)
        tmp.append(math.exp(-(d * d) / (2 * s * s)))
    tot = 0.0
    for v in tmp:
        tot += v
    return [v / tot for v in tmp]


def vector_mean_wind(obs: Iterable[dict]) -> dict:
    ue = vn = s = 0.0
    n = 0
    for o in obs or []:
        if not o or not finite(o.get("u")) or not finite(o.get("dir")):
            continue
        ue += -o["u"] * math.sin(o["dir"] * DEG)
        vn += -o["u"] * math.cos(o["dir"] * DEG)
        s += o["u"]
        n += 1
    if not n:
        return {"u": math.nan, "dir": math.nan, "scalar": math.nan, "n": 0}
    ue /= n
    vn /= n
    return {"u": math.hypot(ue, vn), "dir": wrap360(math.atan2(-ue, -vn) / DEG), "scalar": s / n, "n": n}


def psi_m(zeta: float) -> float:
    if zeta < 0:
        x = math.pow(1 - 16 * zeta, 0.25)
        return 2 * math.log((1 + x) / 2) + math.log((1 + x * x) / 2) - 2 * math.atan(x) + math.pi / 2
    return -5 * min(zeta, 1)


def phi_h(zeta: float) -> float:
    return 1 / math.sqrt(1 - 16 * zeta) if zeta < 0 else 1 + 5 * min(zeta, 1)


def ustar_hat(L: float, z0: float = MD["z0_m"], d: float = MD["d_m"], z0r: float = MD["z0r_m"],
              zb: float = MD["zb_m"], kappa: float = MD["kappa"]) -> float:
    iL = 1 / L if finite(L) and L != 0 else 0.0
    P = psi_m
    usr = kappa / (math.log(10 / z0r) - P(10 * iL) + P(z0r * iL))
    ub = (usr / kappa) * (math.log(zb / z0r) - P(zb * iL) + P(z0r * iL))
    return kappa * ub / (math.log((zb - d) / z0) - P((zb - d) * iL) + P(z0 * iL))


def u_hat(z: float, turb: dict) -> float:
    zz = max(z, turb["Hbar"], turb["d"] + 2 * turb["z0"])
    iL = turb.get("invL") or 0.0
    return (turb["ustar_hat"] / turb["kappa"]) * (math.log((zz - turb["d"]) / turb["z0"]) - psi_m((zz - turb["d"]) * iL)
                                                  + psi_m(turb["z0"] * iL))


def k_hat_mo(z: float, turb: dict) -> float:
    ze = max(z, turb["Hbar"])
    if ze >= turb["h_eff"]:
        return 0.0
    zh = ze - turb["d"]
    lid = 1 - ze / turb["h_eff"]
    return turb["kappa"] * turb["ustar_hat"] * zh / phi_h(zh * (turb.get("invL") or 0.0)) * lid * lid


def turb_params(cls: str, z0: float | None = None, d: float | None = None, Hbar: float | None = None,
                h_eff: float | None = None, h_min: float | None = None) -> dict:
    c = met_class(cls)
    zz0 = z0 if finite(z0) else MD["z0_m"]
    dd = d if finite(d) else MD["d_m"]
    H = Hbar if finite(Hbar) else MD["Hbar_m"]
    L = obukhov_length(c, zz0)
    return {"cls": c, "group": stability_group(c), "L": L, "invL": 1 / L if finite(L) else 0.0,
            "ustar_hat": ustar_hat(L, zz0, dd, MD["z0r_m"], MD["zb_m"], MD["kappa"]),
            "h_eff": h_eff if finite(h_eff) else mixing_height(c, h_min=h_min),
            "z0": zz0, "d": dd, "Hbar": H, "Sct": MD["Sct"], "lambda": MD["lambda_m"], "kmin": MD["kmin_m"],
            "kappa": MD["kappa"], "z0r": MD["z0r_m"], "zb": MD["zb_m"]}


def j_no2(sw: float | None) -> float:
    G = max(0.0, sw) if finite(sw) else 0.0
    return max(0.0, 1.05 * (1.47e-5 * G - 4.84e-9 * G * G))


def k_no_o3(temp_c: float | None, p_hpa: float = 1013.25) -> float:
    T = (temp_c if finite(temp_c) else 15) + 273.15
    return 3.0e-12 * math.exp(-1500 / T) * (7.2429e18 * p_hpa / T) * 1e-9


# ================================================================== chemistry.js
CHEM_VM = 8.314462618 * 293.15 / 101.325
PPB = {"no2": 46.0055 / CHEM_VM, "nox": 46.0055 / CHEM_VM, "no": 30.0061 / CHEM_VM, "o3": 47.9982 / CHEM_VM,
       "so2": 64.0638 / CHEM_VM, "co": 28.0101 / CHEM_VM, "c6h6": 78.11184 / CHEM_VM}
CHEM_TAU_DEFAULT = 60.0


def no2_chemistry(nox_inc: float = 0, no2_bg: float = 0, nox_bg: float = 0, o3_bg: float = 0,
                  tau: float = CHEM_TAU_DEFAULT, J: float = 0, k: float | None = None, f_no2: float = MD["f_no2"]) -> dict:
    """Riccati finite-reaction-time NO-NO2-O3 scheme with conserved oxidant (no2Chemistry)."""
    if k is None:
        k = k_no_o3(15)
    P = PPB
    dN = max(0.0, nox_inc or 0) / P["no2"]
    Nb = max(0.0, nox_bg or 0) / P["no2"]
    xb = max(0.0, no2_bg or 0) / P["no2"]
    ob = max(0.0, o3_bg or 0) / P["o3"]
    N = Nb + dN
    X = ob + xb + f_no2 * dN
    x0 = xb + f_no2 * dN
    if not (tau > 0) or not (k > 0):
        x = x0
    else:
        A = max(0.0, J or 0) / k
        s = N + X + A
        D = math.sqrt(max(s * s - 4 * N * X, 1e-12))
        x1, x2 = 0.5 * (s - D), 0.5 * (s + D)
        if tau == math.inf:
            x = x1
        else:
            den = x0 - x2
            if abs(den) < 1e-12:
                x = x1
            else:
                E = ((x0 - x1) / den) * math.exp(-k * D * tau)
                x = (x1 - x2 * E) / (1 - E)
    x = clamp(x, 0, min(N, X))
    return {"no2": x * P["no2"], "no": (N - x) * P["no"], "o3": (X - x) * P["o3"], "nox": N * P["no2"], "ox": X}


EAQI_BANDS = {"scheme": "eea2024", "pm25": [5, 15, 50, 90, 140], "pm10": [15, 45, 120, 195, 270],
              "no2": [10, 25, 60, 100, 150], "o3": [60, 100, 120, 160, 180], "so2": [20, 40, 125, 190, 275],
              "colors": ["#50F0E6", "#50CCAA", "#F0E641", "#FF5050", "#960032", "#7D2181"]}
EAQI_BANDS_ISZZ = {"scheme": "iszz", "pm25": [10, 20, 25, 50, 75], "pm10": [20, 40, 50, 100, 150],
                   "no2": [40, 90, 120, 230, 340], "o3": [50, 100, 130, 240, 380], "so2": [100, 200, 350, 500, 750],
                   "colors": ["#55EFE5", "#54CAAA", "#EFE558", "#FE5355", "#940D36", "#7D2181"]}


def eaqi(pollutant: str, value: float | None, scheme: str = "eea2024") -> dict:
    B = EAQI_BANDS_ISZZ if scheme == "iszz" else EAQI_BANDS
    lim = B.get(pollutant)
    if not lim or not finite(value):
        return {"level": 0, "color": "#6F6F6F"}
    level = 1
    while level <= len(lim) and value > lim[level - 1]:
        level += 1
    return {"level": level, "color": B["colors"][level - 1]}


# ================================================================== emissions.js
EF_DEFAULT = {"nox": 0.50, "pm10_exh": 0.017, "pm10_nonexh": 0.029, "pm10_resusp": 0.056, "pm25": 0.032, "co": 0.49,
              "c6h6": 0.0036, "pm25_exh": 0.017, "pm25_nonexh": 0.015, "pm25_resusp": 0.056 * 0.15 / 0.62}
EM_SHARES = {
    "brake": {"pm10": (0.0122 * 0.98) / (0.0184 + 0.0075), "pm25": (0.0122 * 0.39) / (0.0093 + 0.0041)},
    "bevBrake": 0.3,
    "bus": {"nox": 0.005 * 3.713 / EF_DEFAULT["nox"], "pm": 0.005 * 0.0636 / EF_DEFAULT["pm10_exh"],
            "co": 0.005 * 1.47 / EF_DEFAULT["co"], "c6h6": 0.0},
    "lez": {"nox": 0.60, "pm": 0.25, "co": 0.60, "c6h6": 0.60},
}
EM_PROFILE_RAW = {
    "weekday": [0.9, 0.6, 0.4, 0.4, 0.6, 1.5, 4.0, 6.8, 7.2, 6.0, 5.3, 5.4, 5.6, 5.7, 6.0, 6.6, 7.2, 7.3, 6.6, 5.2, 3.9,
                3.0, 2.3, 1.5],
    "saturday": [2.72, 2.08, 1.49, 1.21, 1.07, 1.52, 2.98, 4.83, 5.35, 4.96, 4.56, 4.50, 4.71, 4.44, 3.81, 3.94, 5.33,
                 6.96, 7.40, 6.61, 5.44, 5.13, 5.04, 3.93],
    "sunday": [4.10, 3.34, 2.32, 1.90, 1.55, 1.55, 1.93, 2.56, 3.15, 3.49, 3.43, 3.45, 3.79, 3.99, 4.01, 4.83, 6.69,
               8.65, 9.27, 7.71, 5.86, 4.60, 3.76, 4.10],
    "day": [1.00, 1.00, 1.00, 1.00, 1.02, 0.90, 0.70],
    "month": [0.95, 0.98, 1.02, 1.02, 1.02, 1.02, 0.93, 0.85, 1.03, 1.03, 1.03, 1.00],
}
EM_MONTH_DAYS = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]


def _em_norm(a: Sequence[float]) -> list[float]:
    s = 0.0
    for v in a:
        s += v
    return [v / s for v in a]


def _profiles() -> dict:
    R = EM_PROFILE_RAW
    day_mean = 0.0
    for v in R["day"]:
        day_mean += v
    day_mean /= 7
    month_mean = 0.0
    for i, v in enumerate(R["month"]):
        month_mean += v * EM_MONTH_DAYS[i]
    month_mean /= 365
    return {"hour": {"weekday": _em_norm(R["weekday"]), "saturday": _em_norm(R["saturday"]),
                     "sunday": _em_norm(R["sunday"])},
            "day": [v / day_mean for v in R["day"]], "month": [v / month_mean for v in R["month"]]}


TRAFFIC_PROFILES = _profiles()
EM_HOLIDAYS_FIXED = {(1, 1), (1, 6), (5, 1), (5, 30), (6, 22), (8, 5), (8, 15), (11, 1), (11, 18), (12, 25), (12, 26)}


def easter(Y: int) -> tuple[int, int]:
    """Gregorian Easter Sunday (Meeus), (month, day)."""
    a, b, c = Y % 19, Y // 100, Y % 100
    d, e = b // 4, b % 4
    f = (b + 8) // 25
    g = (b - f + 1) // 3
    h = (19 * a + b - d - g + 15) % 30
    i, k = c // 4, c % 4
    l = (32 + 2 * e + 2 * i - h - k) % 7
    m = (a + 11 * h + 22 * l) // 451
    x = h + l - 7 * m + 114
    return x // 31, x % 31 + 1


def is_holiday(year: int, month: int, day: int) -> bool:
    if (month, day) in EM_HOLIDAYS_FIXED:
        return True
    em, ed = easter(year)
    e = dt.date(year, em, ed)
    x = dt.date(year, month, day)
    return x in (e + dt.timedelta(days=1), e + dt.timedelta(days=60))


def day_type(p: dict) -> str:
    if p["dow"] == 6 or is_holiday(p["year"], p["month"], p["day"]):
        return "sunday"
    return "saturday" if p["dow"] == 5 else "weekday"


def traffic_factor(t: Any, month: bool = True) -> float:
    p = local_parts(t)
    typ = day_type(p)
    TP = TRAFFIC_PROFILES
    fd = TP["day"][6] if typ == "sunday" else TP["day"][p["dow"]]
    return 24 * TP["hour"][typ][p["hour"]] * fd * (TP["month"][p["month"] - 1] if month else 1)


EM_MEASURES_TODAY = {"lez": False, "evShare": 0, "eBus": False, "carFreeMiramarska": False, "trafficPct": 100,
                     "trafficA": 100, "trafficB": 100, "congestion": False, "resuspension": False}


def measure_factors(measures: dict | None = None) -> dict:
    m = {**EM_MEASURES_TODAY, **(measures or {})}
    try:
        ev = float(m["evShare"] or 0)
    except (TypeError, ValueError):
        ev = 0.0
    ev = clamp(ev / 100, 0, 1)                         # percent -> fraction
    S = EM_SHARES

    def lez(k):
        return S["lez"][k] if m["lez"] else 1

    def bus(k):
        return 1 - S["bus"][k] if m["eBus"] else 1

    def pct(v):
        try:
            v = float(v)
        except (TypeError, ValueError):
            return 1.0
        return max(0.0, v) / 100 if math.isfinite(v) else 1.0

    pm_exh = (1 - ev) * lez("pm") * bus("pm")
    allf = pct(m["trafficPct"])
    return {
        "exhaust": {"nox": (1 - ev) * lez("nox") * bus("nox"), "pm10": pm_exh, "pm25": pm_exh,
                    "co": (1 - ev) * lez("co") * bus("co"), "c6h6": (1 - ev) * lez("c6h6") * bus("c6h6")},
        "nonexhaust": {"pm10": 1 - ev * S["brake"]["pm10"] * (1 - S["bevBrake"]),
                       "pm25": 1 - ev * S["brake"]["pm25"] * (1 - S["bevBrake"])},
        "resuspension": bool(m["resuspension"]), "congestion": bool(m["congestion"]),
        "byGroup": {"A": allf * pct(m["trafficA"]), "B": 0.0 if m["carFreeMiramarska"] else allf * pct(m["trafficB"]),
                    "C": allf},
        "evShare": ev,
    }


EM_CONGESTION = {"factor": 2.5, "hours": [7, 8, 15, 16, 17], "share": {"A": 0.21, "B": 0.37}}   # calibrate.py congestion_share
EM_HEAT_MIX = {"gas": 0.47, "oil": 0.08, "wood": 0.07}
EM_HEAT_EF = {"gas": {"nox": 51, "co": 26, "pm10": 1.2, "pm25": 1.2}, "oil": {"nox": 51, "co": 57, "pm10": 1.9, "pm25": 1.9},
              "wood": {"nox": 50, "co": 4000, "pm10": 760, "pm25": 740}}


def _mix_ef(p: str) -> float:
    s = 0.0
    for f in EM_HEAT_MIX:
        s += EM_HEAT_MIX[f] * EM_HEAT_EF[f][p]
    return s


EM_HEATING = {
    "months": [10, 11, 12, 1, 2, 3],
    "rate": {"nox": 1.0, "pm10": 2.0, "pm25": 2.0 * _mix_ef("pm25") / _mix_ef("pm10"),
             "co": 1.0 * _mix_ef("co") / _mix_ef("nox"), "c6h6": 0.0},
    "hour": [0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.30, 0.60, 0.80, 0.80, 0.60, 0.30,
             0.30, 0.30, 0.30, 0.30, 0.40, 0.60, 0.80, 1.00, 1.00, 1.00, 0.60, 0.30],
}


def heating_on(setting: Any, month: int) -> bool:
    if setting is True:
        return True
    if setting == "auto":
        return month in EM_HEATING["months"]
    return False


def group_strengths(pollutant: str, t: Any, measures: dict | None = None, heating: Any = False, ef: dict | None = None,
                    heating_scale: float = 1.0, congestion_share: dict | None = None) -> dict:
    """q_k [g m-1 s-1 per 10 000 veh/day for A-C, g m-2 s-1 for D] (groupStrengths)."""
    p = "nox" if pollutant in ("no2", "no") else pollutant
    out = {"A": 0.0, "B": 0.0, "C": 0.0, "D": 0.0}
    if p not in ("nox", "pm10", "pm25", "co", "c6h6"):
        return out
    mf = measure_factors(measures)
    e = {**EF_DEFAULT, **(ef or {})}
    exh = e["nox"] if p == "nox" else e["pm10_exh"] if p == "pm10" else e["pm25_exh"] if p == "pm25" else e[p]
    ne = e["pm10_nonexh"] if p == "pm10" else e["pm25_nonexh"] if p == "pm25" else 0.0
    rs = 0.0 if not mf["resuspension"] else e["pm10_resusp"] if p == "pm10" else e["pm25_resusp"] if p == "pm25" else 0.0
    lp = local_parts(t)
    queue = mf["congestion"] and day_type(lp) == "weekday" and lp["hour"] in EM_CONGESTION["hours"]
    share = congestion_share or EM_CONGESTION["share"]
    veh = MD["aadt_unit"] * traffic_factor(t) / 24
    for g in ("A", "B", "C"):
        cong = 1 + (EM_CONGESTION["factor"] - 1) * (share.get(g) or 0) if queue and g != "C" else 1
        EF = exh * mf["exhaust"][p] * cong + ne * mf["nonexhaust"].get(p, 1) + rs
        out[g] = veh * EF / 3.6e6 * mf["byGroup"][g]
    if heating_on(heating, lp["month"]):
        out["D"] = EM_HEATING["rate"][p] * 1e-6 * EM_HEATING["hour"][lp["hour"]] * heating_scale
    return out


# ================================================================== fallback.js
FB_RADIUS, FB_SPACING, FB_HEAT_CELL = 800.0, 4.0, 10.0
FB_HS_ROAD, FB_HS_HEAT, FB_SZ0, FB_XMIN, FB_YCUT, FB_IMAGES = 0.5, 8.0, 2.0, 0.5, 6.0, 3
FB_EXP_MAX = 40.0   # image terms below exp(-40) are skipped (speed only)
FB_CANYON_RANGE, FB_CANYON_RAY, FB_CANYON_HW, FB_OSPM_LAMBDA = 60.0, 80.0, 0.3, 0.1
FB_QUEUE = (15.0, 75.0)
FB_GROUPS = {"A": 0, "B": 1, "C": 2}
FB_SYC = {"A": 0.32, "B": 0.32, "C": 0.22, "D": 0.16, "E": 0.11, "F": 0.11}   # σyB <= c·x (cheap lateral bound)


def briggs(cls: str, x: float) -> tuple[float, float]:
    if cls in ("A", "B"):
        return 0.32 * x / math.sqrt(1 + 0.0004 * x), 0.24 * x * math.sqrt(1 + 0.001 * x)
    if cls == "C":
        return 0.22 * x / math.sqrt(1 + 0.0004 * x), 0.20 * x
    if cls == "D":
        return 0.16 * x / math.sqrt(1 + 0.0004 * x), 0.14 * x / math.sqrt(1 + 0.0003 * x)
    return 0.11 * x / math.sqrt(1 + 0.0004 * x), 0.08 * x / math.sqrt(1 + 0.0015 * x)


def _seg_x(p1, p2, p3, p4):
    d1x, d1z, d2x, d2z = p2[0] - p1[0], p2[1] - p1[1], p4[0] - p3[0], p4[1] - p3[1]
    den = d1x * d2z - d1z * d2x
    if abs(den) < 1e-12:
        return None
    s = ((p3[0] - p1[0]) * d2z - (p3[1] - p1[1]) * d2x) / den
    u = ((p3[0] - p1[0]) * d1z - (p3[1] - p1[1]) * d1x) / den
    if s < 0 or s > 1 or u < 0 or u > 1:
        return None
    return (p1[0] + s * d1x, p1[1] + s * d1z)


def _ray_hit(ox, oz, dx, dz, a, b) -> float:
    ex, ez = b[0] - a[0], b[1] - a[1]
    den = dx * ez - dz * ex
    if abs(den) < 1e-12:
        return math.inf
    tt = ((a[0] - ox) * ez - (a[1] - oz) * ex) / den
    u = ((a[0] - ox) * dz - (a[1] - oz) * dx) / den
    return tt if tt > 1e-9 and 0 <= u <= 1 else math.inf


class FallbackModel:
    """Gaussian line/area sources (Briggs urban) + OSPM-type canyon term (FallbackModel in fallback.js)."""

    def __init__(self, env: dict, radius: float = FB_RADIUS, spacing: float = FB_SPACING, heat_cell: float = FB_HEAT_CELL,
                 receptor: tuple[float, float, float] = RECEPTOR, h_min: float | None = None):
        env = env or {}
        self.radius, self.spacing, self.heat_cell = radius, spacing, heat_cell
        self.rx, self.ry, self.rz = receptor
        self.h_min = h_min if finite(h_min) else MD["h_min_m"]
        self.roads = [r for r in env.get("roads") or [] if r and r.get("g") in FB_GROUPS and (r.get("aadt") or 0) > 0
                      and r.get("p") and len(r["p"]) > 1]
        blds = env["buildings"] if env.get("buildings") is not None else [
            b for b in env.get("prisms") or [] if not (b and b.get("s") is not None and b["s"] < 0.5)]
        self.buildings = [b for b in blds if b and b.get("p") and len(b["p"]) > 2 and (b.get("h") or 0) > 0]
        self.heating = [hp for hp in env.get("heating") or [] if hp and hp.get("p") and len(hp["p"]) > 2]
        self._bb = [bounds(b["p"]) for b in self.buildings]
        self.center = self._intersection()
        self._build_sources()
        self.canyons = [self._canyon(gi) for gi in range(3)]
        self._cache: dict = {}

    def _intersection(self):
        def segs(g):
            out = []
            for rd in self.roads:
                if rd["g"] != g:
                    continue
                for i in range(len(rd["p"]) - 1):
                    a, b = rd["p"][i], rd["p"][i + 1]
                    if seg_dist(self.rx, self.rz, a[0], a[1], b[0], b[1]) < 150:
                        out.append((a, b))
            return out
        A, B = segs("A"), segs("B")
        sx = sz = 0.0
        n = 0
        for a1, a2 in A:
            for b1, b2 in B:
                p = _seg_x(a1, a2, b1, b2)
                if p:
                    sx += p[0]
                    sz += p[1]
                    n += 1
        return (sx / n, sz / n) if n else None

    def _build_sources(self) -> None:
        X, Z, W, H, S, G, Q = [], [], [], [], [], [], []
        R2 = self.radius * self.radius
        C = self.center
        for rd in self.roads:
            gi = FB_GROUPS[rd["g"]]
            a = rd["aadt"] / MD["aadt_unit"]
            w = rd.get("w") or 0
            sy0 = (w if w > 0 else 3.25 * (rd["l"] if (rd.get("l") or 0) > 0 else 2)) / 2
            o = rd.get("o") or 0
            for i in range(len(rd["p"]) - 1):
                x1, z1 = rd["p"][i][0], rd["p"][i][1]
                x2, z2 = rd["p"][i + 1][0], rd["p"][i + 1][1]
                L = math.hypot(x2 - x1, z2 - z1)
                if not (L > 0):
                    continue
                n = max(1, math.ceil(L / self.spacing))
                ds = L / n
                for k in range(n):
                    s = (k + 0.5) / n
                    px, pz = x1 + (x2 - x1) * s, z1 + (z2 - z1) * s
                    ex, ez = px - self.rx, pz - self.rz
                    if ex * ex + ez * ez > R2:
                        continue
                    qf = 0.0
                    if C and gi < 2:
                        d = math.hypot(px - C[0], pz - C[1])
                        if FB_QUEUE[0] <= d <= FB_QUEUE[1]:
                            if o == 0:
                                qf = 0.5
                            else:
                                tx, tz = o * (x2 - x1) / L, o * (z2 - z1) / L
                                qf = 1.0 if tx * (C[0] - px) + tz * (C[1] - pz) > 0 else 0.0
                    X.append(px); Z.append(pz); W.append(a * ds); H.append(FB_HS_ROAD); S.append(sy0); G.append(gi); Q.append(qf)
        c = self.heat_cell
        for hp in self.heating:
            wt = (hp["w"] if finite(hp.get("w")) else 1) * c * c
            bb = bounds(hp["p"])
            i0, i1 = math.ceil((bb["x0"] - c / 2) / c), math.floor((bb["x1"] - c / 2) / c)
            j0, j1 = math.ceil((bb["z0"] - c / 2) / c), math.floor((bb["z1"] - c / 2) / c)
            for j in range(j0, j1 + 1):
                for i in range(i0, i1 + 1):
                    px, pz = i * c + c / 2, j * c + c / 2
                    ex, ez = px - self.rx, pz - self.rz
                    if ex * ex + ez * ez > R2 or not point_in_poly(px, pz, hp["p"]):
                        continue
                    X.append(px); Z.append(pz); W.append(wt); H.append(FB_HS_HEAT); S.append(c / 2); G.append(3); Q.append(0.0)
        self.src = {"x": X, "z": Z, "w": W, "hs": H, "sy0": S, "g": G, "q": Q, "n": len(X)}

    def _wall(self, ox, oz, dx, dz):
        best, h = math.inf, 0.0
        reach = FB_CANYON_RAY
        for b, bb in zip(self.buildings, self._bb):
            if (bb["x1"] < min(ox, ox + dx * reach) - 1 or bb["x0"] > max(ox, ox + dx * reach) + 1
                    or bb["z1"] < min(oz, oz + dz * reach) - 1 or bb["z0"] > max(oz, oz + dz * reach) + 1):
                continue
            p = b["p"]
            for i in range(len(p)):
                tt = _ray_hit(ox, oz, dx, dz, p[i], p[(i + 1) % len(p)])
                if tt < best and tt <= reach:
                    best, h = tt, b["h"]
        return {"dist": best, "h": h} if best <= reach else None

    def _canyon(self, gi: int):
        best, P0, seg = math.inf, None, None
        for rd in self.roads:
            if FB_GROUPS[rd["g"]] != gi:
                continue
            for i in range(len(rd["p"]) - 1):
                ax, az = rd["p"][i][0], rd["p"][i][1]
                bx, bz = rd["p"][i + 1][0], rd["p"][i + 1][1]
                dx, dz = bx - ax, bz - az
                L2 = dx * dx + dz * dz
                if not (L2 > 0):
                    continue
                s = clamp(((self.rx - ax) * dx + (self.rz - az) * dz) / L2, 0, 1)
                px, pz = ax + dx * s, az + dz * s
                d = math.hypot(self.rx - px, self.rz - pz)
                if d < best:
                    best, P0, seg = d, (px, pz), (dx, dz, math.sqrt(L2))
        if P0 is None or best > FB_CANYON_RANGE:
            return None
        if best > 0.1:
            nx, nz = (self.rx - P0[0]) / best, (self.rz - P0[1]) / best
        else:
            nx, nz = -seg[1] / seg[2], seg[0] / seg[2]
        near, far = self._wall(P0[0], P0[1], nx, nz), self._wall(P0[0], P0[1], -nx, -nz)
        if not near or not far or near["dist"] <= best:
            return None
        Wc, Hc = near["dist"] + far["dist"], (near["h"] + far["h"]) / 2
        if Hc / Wc < FB_CANYON_HW:
            return None
        Qu = 0.0
        for rd in self.roads:
            if FB_GROUPS[rd["g"]] != gi:
                continue
            dmin = math.inf
            for i in range(len(rd["p"]) - 1):
                dmin = min(dmin, seg_dist(P0[0], P0[1], rd["p"][i][0], rd["p"][i][1], rd["p"][i + 1][0], rd["p"][i + 1][1]))
            if dmin <= max(near["dist"], far["dist"]):
                Qu += rd["aadt"] / MD["aadt_unit"]
        return {"nx": nx, "nz": nz, "W": Wc, "H": Hc, "hNear": near["h"], "hFar": far["h"], "Q": Qu, "dist": best}

    def _kernel(self, m: int, rx: float, ry: float, rz: float, bx: float, bz: float, c: str, h: float):
        S = self.src
        dx, dz = rx - S["x"][m], rz - S["z"][m]
        x = dx * bx + dz * bz
        if x <= FB_XMIN:
            return 0.0, x
        y = -dx * bz + dz * bx
        sy0 = S["sy0"][m]
        if abs(y) > FB_YCUT * (sy0 + FB_SYC[c] * x):
            return 0.0, x
        syb, szb = briggs(c, x)
        sy = math.sqrt(sy0 * sy0 + syb * syb)
        if abs(y) > FB_YCUT * sy:
            return 0.0, x
        sz = math.sqrt(FB_SZ0 * FB_SZ0 + szb * szb)
        hs, s2 = S["hs"][m], 2 * sz * sz
        V = 0.0
        nI = FB_IMAGES if sz > h / 4 else 0
        for n in range(-nI, nI + 1):
            a, b = ry - hs + 2 * n * h, ry + hs + 2 * n * h
            ea, eb = (a * a) / s2, (b * b) / s2
            if ea < FB_EXP_MAX:
                V += math.exp(-ea)
            if eb < FB_EXP_MAX:
                V += math.exp(-eb)
        return S["w"][m] / (2 * math.pi * sy * sz) * math.exp(-(y * y) / (2 * sy * sy)) * V, x

    def receptor(self, dir_deg: float, cls: str) -> dict:
        c = met_class(cls)
        key = (round(wrap360(dir_deg) * 10), c)
        if key not in self._cache:
            self._cache[key] = self._receptor(wrap360(dir_deg), c)
        r = self._cache[key]
        return {k: (list(v) if isinstance(v, list) else v) for k, v in r.items()}

    def _receptor(self, dir_deg: float, c: str) -> dict:
        out = {"gamma": [0.0] * 4, "age": [0.0] * 4, "queue": [0.0] * 4, "canyon": [0.0] * 4, "n": 0}
        h = mixing_height(c, h_min=self.h_min)
        bx, bz = -math.sin(dir_deg * DEG), math.cos(dir_deg * DEG)
        S = self.src
        for m in range(S["n"]):
            g, x = self._kernel(m, self.rx, self.ry, self.rz, bx, bz, c, h)
            if not g:
                continue
            k = S["g"][m]
            out["gamma"][k] += g
            out["age"][k] += g * x
            out["queue"][k] += g * S["q"][m]
            out["n"] += 1
        turb = turb_params(c)
        for gi in range(3):
            cy = self.canyons[gi]
            if not cy:
                continue
            bn = bx * cy["nx"] + bz * cy["nz"]
            leeward = bn < 0
            Lv = 2 * (cy["hNear"] if leeward else cy["hFar"])
            if not leeward and Lv < cy["W"]:
                continue
            Lr, Lt = min(Lv, cy["W"]), min(Lv / 2, cy["W"])
            if not (Lt > 0):
                continue
            swt = FB_OSPM_LAMBDA * u_hat(cy["H"], turb)
            gr = cy["Q"] * Lr / (cy["W"] * swt * Lt) * abs(bn)
            out["gamma"][gi] += gr
            out["age"][gi] += gr * (Lr * cy["H"]) / (swt * Lt)
            out["canyon"][gi] += gr
        return out

    def _rotated(self, dir_deg: float) -> dict:
        """Sources in wind coordinates, sorted by the along-wind coordinate (FallbackModel._rotated)."""
        bx, bz = -math.sin(dir_deg * DEG), math.cos(dir_deg * DEG)
        S = self.src
        along = [S["x"][m] * bx + S["z"][m] * bz for m in range(S["n"])]
        idx = sorted(range(S["n"]), key=lambda m: along[m])
        return {"bx": bx, "bz": bz, "n": S["n"], "a": [along[m] for m in idx],
                "c": [-S["x"][m] * bz + S["z"][m] * bx for m in idx], "w": [S["w"][m] for m in idx],
                "hs": [S["hs"][m] for m in idx], "sy0": [S["sy0"][m] for m in idx], "g": [S["g"][m] for m in idx]}

    def slice(self, dir_deg: float, cls: str, height: float, grid: dict) -> list[float]:
        """Γ on a horizontal slice, cell centres, index ((j·nx + i)·4 + k) (FallbackModel.slice)."""
        import bisect
        c = met_class(cls)
        h = mixing_height(c, h_min=self.h_min)
        x0, z0, dx, nx, nz = grid["x0"], grid["z0"], grid["dx"], grid["nx"], grid["nz"]
        res = [0.0] * (nx * nz * 4)
        R = self._rotated(wrap360(dir_deg))
        cyc = FB_SYC[c]
        for j in range(nz):
            z = z0 + (j + 0.5) * dx
            for i in range(nx):
                x = x0 + (i + 0.5) * dx
                ar, cr = x * R["bx"] + z * R["bz"], -x * R["bz"] + z * R["bx"]
                lo = bisect.bisect_left(R["a"], ar - FB_XMIN)
                acc = [0.0] * 4
                for m in range(lo):
                    xx = ar - R["a"][m]
                    if xx <= FB_XMIN:
                        continue
                    yy, sy0 = cr - R["c"][m], R["sy0"][m]
                    if abs(yy) > FB_YCUT * (sy0 + cyc * xx):
                        continue
                    syb, szb = briggs(c, xx)
                    sy = math.sqrt(sy0 * sy0 + syb * syb)
                    if abs(yy) > FB_YCUT * sy:
                        continue
                    sz = math.sqrt(FB_SZ0 * FB_SZ0 + szb * szb)
                    hs, s2 = R["hs"][m], 2 * sz * sz
                    V = 0.0
                    nI = FB_IMAGES if sz > h / 4 else 0
                    for n in range(-nI, nI + 1):
                        aa, bb = height - hs + 2 * n * h, height + hs + 2 * n * h
                        ea, eb = (aa * aa) / s2, (bb * bb) / s2
                        if ea < FB_EXP_MAX:
                            V += math.exp(-ea)
                        if eb < FB_EXP_MAX:
                            V += math.exp(-eb)
                    acc[R["g"][m]] += R["w"][m] / (2 * math.pi * sy * sz) * math.exp(-(yy * yy) / (2 * sy * sy)) * V
                o = (j * nx + i) * 4
                res[o:o + 4] = acc
        return res


# ================================================================== model.js
def increment(gamma: Sequence[float], age: Sequence[float], q: dict, u10: float, beta: float, U0: float) -> dict:
    """ΔC = 1e6 β Σ q Γ / U_eff and τ = Σ q A / (U_eff Σ q Γ) for one source (increment() with an explicit cal)."""
    qs = [q.get("A", 0) or 0, q.get("B", 0) or 0, q.get("C", 0) or 0, q.get("D", 0) or 0]
    U = u_eff(u10, U0)
    by = [0.0] * 4
    num = den = 0.0
    for k in range(4):
        by[k] += 1e6 * beta * qs[k] * (gamma[k] or 0) / U
        num += beta * qs[k] * (age[k] or 0) / (U * U)
        den += beta * qs[k] * (gamma[k] or 0) / U
    return {"total": by[0] + by[1] + by[2] + by[3], "byGroup": by, "tau": num / den if den > 0 else CHEM_TAU_DEFAULT}


def metrics(obs: Sequence[float], mod: Sequence[float], floor: float = 1.0) -> dict:
    """Chang & Hanna (2004) statistics, same conventions as metrics() in model.js."""
    o, p = [], []
    for a, b in zip(obs, mod):
        if finite(a) and finite(b):
            o.append(float(a))
            p.append(float(b))
    n = len(o)
    if not n:
        return {k: math.nan for k in ("FB", "NMSE", "MG", "VG", "FAC2", "NAD", "R", "RMSE", "meanObs", "meanMod")} | {"n": 0}
    so = sp = 0.0
    for i in range(n):
        so += o[i]
        sp += p[i]
    mo, mp = so / n, sp / n
    se = sa = lg = lg2 = f2 = cov = vo = vp = 0.0
    for i in range(n):
        d = o[i] - p[i]
        se += d * d
        sa += abs(d)
        lo, lp = math.log(max(o[i], floor)), math.log(max(p[i], floor))
        lg += lo - lp
        lg2 += (lo - lp) * (lo - lp)
        ratio = max(p[i], floor) / max(o[i], floor)
        if 0.5 <= ratio <= 2:
            f2 += 1
        cov += (o[i] - mo) * (p[i] - mp)
        vo += (o[i] - mo) * (o[i] - mo)
        vp += (p[i] - mp) * (p[i] - mp)
    return {"FB": (mo - mp) / (0.5 * (mo + mp)) if mo + mp else math.nan,
            "NMSE": (se / n) / (mo * mp) if mo * mp else math.nan,
            "MG": math.exp(lg / n), "VG": math.exp(lg2 / n), "FAC2": f2 / n,
            "NAD": (sa / n) / (mo + mp) if mo + mp else math.nan,
            "R": cov / math.sqrt(vo * vp) if vo > 0 and vp > 0 else math.nan,
            "n": n, "RMSE": math.sqrt(se / n), "meanObs": mo, "meanMod": mp}


MOD_MQI = {"no2": (0.24, 200, 0.20), "o3": (0.18, 120, 0.79), "pm10": (0.28, 50, 0.25), "pm25": (0.36, 25, 0.50)}


def mqi(obs: Sequence[float], mod: Sequence[float], pollutant: str) -> float:
    P = MOD_MQI.get(pollutant)
    if not P:
        return math.nan
    Ur, RV, al = P
    se = su = 0.0
    n = 0
    for a, b in zip(obs, mod):
        if not (finite(a) and finite(b)):
            continue
        d = a - b
        se += d * d
        su += Ur * Ur * ((1 - al * al) * a * a + al * al * RV * RV)
        n += 1
    return math.sqrt(se / n) / (2 * math.sqrt(su / n)) if n else math.nan


def gamma_table(fb: FallbackModel, classes: Sequence[str] = MET_CLASSES) -> dict:
    """{cls: [16 dirs] -> receptor dict} of the fallback, the Python analogue of the LUT."""
    return {c: [fb.receptor(d, c) for d in DIRS16] for c in classes}


def smooth_gamma(rows: Sequence[dict], dir_deg: float, u10: float) -> dict:
    """Kernel-weighted Γ, A and queue over the 16 run directions (ReceptorModel.gammaAt, one source)."""
    w = direction_weights(dir_deg, u10)
    out = {"gamma": [0.0] * 4, "age": [0.0] * 4, "queue": [0.0] * 4}
    for j, wj in enumerate(w):
        if not (wj > 0):
            continue
        r = rows[j]
        for k in range(4):
            out["gamma"][k] += wj * (r["gamma"][k] or 0)
            out["age"][k] += wj * (r["age"][k] or 0)
            if "queue" in r and r["queue"]:
                out["queue"][k] += wj * r["queue"][k]
    return out


def load_env(path: Path = SRC_DATA / "env.json") -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


# ================================================================== parity vectors
def _enc(v: Any) -> Any:
    """JSON-safe encoding: ±Infinity and NaN become strings (decoded by models.test.js)."""
    if isinstance(v, float):
        if math.isnan(v):
            return "NaN"
        if math.isinf(v):
            return "Infinity" if v > 0 else "-Infinity"
        return v
    if isinstance(v, dict):
        return {k: _enc(x) for k, x in v.items()}
    if isinstance(v, (list, tuple)):
        return [_enc(x) for x in v]
    return v


def synthetic_env() -> dict:
    """Small deterministic geometry for the fallback parity test: an E-W avenue (A), a N-S street (B) crossing it,
    a side street (C), a street canyon for B (two slabs), and a heating polygon."""
    return {
        "roads": [
            {"p": [[-300, 45], [300, 45]], "g": "A", "aadt": 23000, "o": 1, "w": 9.8, "l": 3},
            {"p": [[300, 60], [-300, 60]], "g": "A", "aadt": 22000, "o": 1, "w": 9.8, "l": 3},
            {"p": [[20, -250], [20, 0], [21, 52], [22, 300]], "g": "B", "aadt": 20000, "o": 0, "w": 13.5, "l": 4},
            {"p": [[-120, -80], [-40, -82], [60, -85]], "g": "C", "aadt": 4000, "o": 0, "w": 6.5, "l": 2},
            {"p": [[0, 0], [5, 5]], "g": None, "aadt": 0},
        ],
        "buildings": [
            {"p": [[-30, -60], [-12, -60], [-12, 30], [-30, 30]], "b": 0, "h": 24, "s": 2022},
            {"p": [[36, -60], [60, -60], [60, 30], [36, 30]], "b": 0, "h": 27, "s": 2022},
            {"p": [[-200, 100], [-150, 100], [-150, 150], [-200, 150]], "b": 0, "h": 12, "s": 0},
        ],
        "heating": [{"p": [[100, 150], [260, 160], [250, 300], [120, 280]], "w": 0.8}],
    }


def build_parity() -> dict:
    rnd = random.Random(20260927)
    V: dict[str, list] = {}
    times = [to_ms(s) for s in ("2025-01-14T08:00Z", "2025-03-30T00:00Z", "2025-03-30T01:00Z", "2025-03-30T02:00Z",
                                "2025-06-21T11:00Z", "2025-08-15T15:00Z", "2025-10-26T00:00Z", "2025-10-26T01:00Z",
                                "2025-10-26T02:00Z", "2025-12-25T18:00Z", "2026-04-06T07:00Z", "2026-06-04T16:00Z",
                                "2024-02-29T12:30Z", "2025-11-18T09:00Z", "2025-07-05T22:00Z", "2025-07-06T13:00Z")]
    V["local_parts"] = [{"in": {"t": t}, "out": local_parts(t)} for t in times]
    V["solar_elevation"] = [{"in": {"t": t}, "out": solar_elevation(t)} for t in times]
    V["stability_class"] = []
    for u in (0.3, 1.0, 1.95, 2.5, 3.3, 4.0, 5.2, 5.8, 7.0):
        for sw in (0, 100, 300, 700, 950, None):
            for cc in (10, 60, 97):
                t = times[rnd.randrange(len(times))]
                V["stability_class"].append({"in": {"u10": u, "sw": sw, "cloud": cc, "t": t},
                                             "out": stability_class(u, sw, cc, t)})
    V["obukhov_length"] = [{"in": {"cls": c, "z0": z0}, "out": obukhov_length(c, z0)}
                           for c in MET_CLASSES + ["AC", "EF"] for z0 in (0.1, 0.5, 1.5)]
    V["mixing_height"] = [{"in": {"cls": c, "blh": blh, "mode": mode, "hMin": 100}, "out": mixing_height(c, blh, mode, 100)}
                          for c in ("B", "D", "F", "EF") for blh in (None, 25.0, 180.0, 900.0) for mode in ("auto", "nwp", "100", "315")]
    V["u_eff"] = [{"in": {"u10": u, "U0": U0}, "out": u_eff(u, U0)} for u in (0, 0.4, 1.7, 5.0, None) for U0 in (1.0, 1.4)]
    V["direction_weights"] = [{"in": {"dir": d, "u10": u}, "out": direction_weights(d, u)}
                              for d in (0, 45, 101.3, 266, 359.9) for u in (0.3, 0.6, 1.2, 2.0, 5.0)]
    V["turb_params"] = []
    for c in MET_CLASSES + ["AC", "D", "EF"]:
        for (z0, d, H) in ((1.5, 7.0, 14.0), (1.4, 8.0, 14.0)):
            tp = turb_params(c, z0, d, H, h_eff=MET_BLH_MEDIAN[met_class(c)] if c != "F" else 100.0)
            V["turb_params"].append({"in": {"cls": c, "z0": z0, "d": d, "Hbar": H, "h_eff": tp["h_eff"]},
                                     "out": {k: tp[k] for k in ("L", "invL", "ustar_hat", "h_eff")}})
    tD = turb_params("D", 1.5, 7.0, 14.0, h_eff=135.0)
    tF = turb_params("F", 1.5, 7.0, 14.0, h_eff=100.0)
    tB = turb_params("B", 1.5, 7.0, 14.0, h_eff=520.0)
    V["most"] = ([{"in": {"fn": "psiM", "x": z}, "out": psi_m(z)} for z in (-2.0, -0.3, -0.01, 0.0, 0.2, 1.0, 3.0)]
                 + [{"in": {"fn": "phiH", "x": z}, "out": phi_h(z)} for z in (-2.0, -0.3, 0.0, 0.5, 2.0)]
                 + [{"in": {"fn": "kHatMO", "x": z, "turb": tt}, "out": k_hat_mo(z, tt)}
                    for tt in (tD, tF, tB) for z in (2.5, 12.0, 30.0, 90.0, 150.0)]
                 + [{"in": {"fn": "uHat", "x": z, "turb": tt}, "out": u_hat(z, tt)} for tt in (tD, tF, tB) for z in (14.0, 40.0)])
    V["j_no2"] = [{"in": {"sw": s}, "out": j_no2(s)} for s in (0, 50, 200, 500, 800, 1000, None)]
    V["k_no_o3"] = [{"in": {"t": tc}, "out": k_no_o3(tc)} for tc in (-10, 0, 15, 30, None)]
    V["vector_mean_wind"] = [{"in": {"list": L}, "out": vector_mean_wind(L)} for L in (
        [{"u": 2, "dir": 350}, {"u": 2, "dir": 10}], [{"u": 1, "dir": 90}, {"u": 3, "dir": 270}],
        [{"u": 1.5, "dir": 45}], [{"u": 2.2, "dir": 200}, {"u": None, "dir": 10}, {"u": 1.0, "dir": 230}])]
    V["no2_chemistry"] = []
    for _ in range(40):
        inp = {"noxInc": rnd.choice([0, 5, 40, 150, 600]) * rnd.random(), "no2Bg": 5 + 30 * rnd.random(),
               "noxBg": 10 + 60 * rnd.random(), "o3Bg": 80 * rnd.random(), "tau": rnd.choice([0, 20, 60, 180, math.inf]),
               "J": rnd.choice([0, 0.002, 0.008]), "k": k_no_o3(rnd.choice([-5, 12, 28])), "fNO2": rnd.choice([0.05, 0.1, 0.2])}
        r = no2_chemistry(inp["noxInc"], inp["no2Bg"], inp["noxBg"], inp["o3Bg"], inp["tau"], inp["J"], inp["k"], inp["fNO2"])
        V["no2_chemistry"].append({"in": inp, "out": r})
    V["ppb"] = [{"in": {"p": p}, "out": PPB[p]} for p in PPB]
    V["eaqi"] = [{"in": {"p": p, "v": v, "scheme": s}, "out": eaqi(p, v, s)}
                 for s in ("eea2024", "iszz") for p in ("no2", "pm10", "pm25", "o3", "so2", "co")
                 for v in (0, 10, 10.01, 25, 45, 60, 100, 140, 151, 400, None)]
    V["traffic_factor"] = [{"in": {"t": t, "month": mo}, "out": traffic_factor(t, mo)} for t in times for mo in (True, False)]
    MS = [{}, {"lez": True}, {"evShare": 30}, {"evShare": 50, "eBus": True}, {"carFreeMiramarska": True, "trafficPct": 80},
          {"trafficA": 120, "trafficB": 50, "congestion": True, "resuspension": True},
          {"lez": True, "evShare": 20, "eBus": True, "congestion": True}]
    V["measure_factors"] = [{"in": {"m": m}, "out": measure_factors(m)} for m in MS]
    V["group_strengths"] = []
    for p in ("nox", "no2", "pm10", "pm25", "co", "c6h6", "o3"):
        for t in (times[0], times[5], times[9], times[11], times[15]):
            for m in (MS[0], MS[5], MS[6]):
                for heat in (False, "auto", True):
                    cs = {"A": 0.3, "B": 0.55}
                    V["group_strengths"].append({"in": {"p": p, "t": t, "m": m, "heating": heat, "congestionShare": cs},
                                                 "out": group_strengths(p, t, m, heat, None, 1.0, cs)})
    env = synthetic_env()
    fb = FallbackModel(env)
    V["fallback_env"] = [{"in": {"env": env}, "out": {"center": list(fb.center) if fb.center else None, "n": fb.src["n"],
                                                     "canyons": fb.canyons}}]
    V["fallback_receptor"] = [{"in": {"dir": d, "cls": c}, "out": fb.receptor(d, c)}
                              for d in (0, 45, 90, 180, 225, 270, 300) for c in ("B", "C", "D", "F", "EF")]
    grid = {"x0": -60, "z0": -60, "dx": 30, "nx": 4, "nz": 4}
    V["fallback_slice"] = [{"in": {"dir": d, "cls": c, "height": 4.0, "grid": grid}, "out": fb.slice(d, c, 4.0, grid)}
                           for d, c in ((45, "D"), (225, "F"))]
    V["increment"] = []
    for _ in range(12):
        g = [rnd.random() * 0.5 for _ in range(4)]
        a = [x * (20 + 80 * rnd.random()) for x in g]
        q = {"A": 6e-5 * rnd.random(), "B": 6e-5 * rnd.random(), "C": 6e-5 * rnd.random(), "D": 1e-6 * rnd.random()}
        u, beta, U0 = rnd.choice([0.2, 1.1, 3.4]), rnd.choice([1.0, 3.7]), rnd.choice([1.2, 1.4])
        V["increment"].append({"in": {"gamma": g, "age": a, "q": q, "u10": u, "beta": beta, "U0": U0},
                               "out": increment(g, a, q, u, beta, U0)})
    V["metrics"] = []
    for _ in range(6):
        n = rnd.randrange(5, 60)
        o = [rnd.gauss(40, 30) for _ in range(n)]
        m = [x * (0.4 + rnd.random() * 1.4) + rnd.gauss(0, 5) for x in o]
        if n > 10:
            o[3] = math.nan
        V["metrics"].append({"in": {"obs": o, "mod": m}, "out": metrics(o, m)})
    V["mqi"] = [{"in": {"obs": e["in"]["obs"], "mod": e["in"]["mod"], "p": p}, "out": mqi(e["in"]["obs"], e["in"]["mod"], p)}
                for e in V["metrics"][:3] for p in ("no2", "pm10", "o3", "pm25")]
    V["chem_sample"] = chem_sample()
    return {"meta": {"generated_utc": dt.datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
                     "generator": "tools/aqmodel.py --write-parity", "tolerance": "1e-6 relative (+1e-12 absolute)",
                     "note": "Infinity/NaN are encoded as strings; times are epoch ms (hour-ending UTC)."},
            "cases": _enc(V)}


def chem_sample(step: int = 26) -> list[dict]:
    """Real 2025 hours for the chemistry parity case and the RMSE test: ZAGREB-1 NOx/NO2, ZAGREB-4 NOx/NO2/O3,
    IFS SW and T2 from data/processed (empty if the tables are absent). Every `step`-th complete hour."""
    import csv
    import gzip
    iszz, ifs = ROOT / "data" / "processed" / "iszz_hourly.csv.gz", ROOT / "data" / "processed" / "ifs_hourly.csv.gz"
    if not (iszz.exists() and ifs.exists()):
        log.warning("chem_sample: processed tables missing, section left empty")
        return []
    obs: dict[str, dict] = {}
    with gzip.open(iszz, "rt", encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            if r["t_utc_end"][:4] == "2025":
                obs.setdefault(r["t_utc_end"], {})[("z1." if r["station"] == "155" else "z4.") + r["param"]] = float(r["value"])
    met: dict[str, dict] = {}
    with gzip.open(ifs, "rt", encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            if r["t_utc_end"][:4] == "2025" and r["sw"] and r["t2"]:
                met[r["t_utc_end"]] = {"sw": float(r["sw"]), "t2": float(r["t2"])}
    need = ("z1.nox", "z1.no2", "z4.nox", "z4.no2", "z4.o3")
    keys = [t for t in sorted(obs) if t in met and all(k in obs[t] for k in need)]
    out = []
    for t in keys[::step]:
        o, m = obs[t], met[t]
        inp = {"noxInc": o["z1.nox"] - o["z4.nox"], "no2Bg": o["z4.no2"], "noxBg": o["z4.nox"], "o3Bg": o["z4.o3"],
               "tau": CHEM_TAU_DEFAULT, "sw": m["sw"], "t2": m["t2"], "fNO2": MD["f_no2"], "obs": o["z1.no2"], "t": t}
        r = no2_chemistry(inp["noxInc"], inp["no2Bg"], inp["noxBg"], inp["o3Bg"], inp["tau"], j_no2(m["sw"]), k_no_o3(m["t2"]),
                          inp["fNO2"])
        out.append({"in": inp, "out": r})
    return out


def write_parity() -> None:
    data = build_parity()
    text = json.dumps(data, separators=(",", ":"), ensure_ascii=False)
    PARITY_JSON.parent.mkdir(parents=True, exist_ok=True)
    _atomic_write(PARITY_JSON, text + "\n")
    js = MODELS_TEST_JS.read_text(encoding="utf-8")
    a, b = js.find(PARITY_BEGIN), js.find(PARITY_END)
    if a < 0 or b < a:
        raise SystemExit(f"markers not found in {MODELS_TEST_JS}")
    js = js[:a + len(PARITY_BEGIN)] + "\nconst MT_PARITY = " + text + ";\n" + js[b:]
    _atomic_write(MODELS_TEST_JS, js)
    n = sum(len(v) for v in data["cases"].values())
    log.info("parity: %d cases in %d sections -> %s and %s", n, len(data["cases"]), PARITY_JSON, MODELS_TEST_JS)


def _atomic_write(path: Path, text: str) -> None:
    fd, tmp = tempfile.mkstemp(dir=str(path.parent), prefix=".tmp-", suffix=path.suffix)
    with os.fdopen(fd, "w", encoding="utf-8") as fh:
        fh.write(text)
    os.chmod(tmp, 0o644)
    os.replace(tmp, path)


# ================================================================== CLI
def main(argv: Sequence[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0], formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--write-parity", action="store_true", help="regenerate the Python↔JS parity vectors")
    ap.add_argument("--receptor", nargs=2, metavar=("DIR", "CLS"), help="fallback Γ at ZAGREB-1 for one direction/class")
    ap.add_argument("--hour", help="print q_k and the fallback increment for one hour (ISO, hour-ending UTC)")
    ap.add_argument("--u10", type=float, default=1.7)
    ap.add_argument("--dir", type=float, default=45)
    ap.add_argument("--sw", type=float)
    ap.add_argument("--cc", type=float, default=50)
    ap.add_argument("--t2", type=float, default=10)
    ap.add_argument("--beta", type=float, default=1.0)
    a = ap.parse_args(argv)
    if a.write_parity:
        write_parity()
    if a.receptor:
        fb = FallbackModel(load_env())
        print(json.dumps({"center": fb.center, "points": fb.src["n"], "canyons": fb.canyons,
                          "receptor": fb.receptor(float(a.receptor[0]), a.receptor[1])}, indent=1))
    if a.hour:
        t = to_ms(a.hour)
        cls = stability_class(a.u10, a.sw, a.cc, t)
        fb = FallbackModel(load_env())
        rows = [fb.receptor(d, cls) for d in DIRS16]
        ga = smooth_gamma(rows, a.dir, a.u10)
        q = group_strengths("nox", t, {}, "auto")
        inc = increment(ga["gamma"], ga["age"], q, a.u10, a.beta, MD["U0"])
        print(json.dumps({"class": cls, "local": local_parts(t), "trafficFactor": traffic_factor(t), "q": q,
                          "gamma": ga["gamma"], "increment": inc}, indent=1))
    if not (a.write_parity or a.receptor or a.hour):
        ap.print_help()
    return 0


if __name__ == "__main__":
    sys.exit(main())
